services:
  postgres:
    container_name: flyfood-postgres
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: "cardapiogo"
      POSTGRES_USER: "cardapiogo"
      POSTGRES_PASSWORD: "cardapiogo"
    ports:
      - "5432:5432"
    volumes:
     - postgres-data:/var/lib/postgresql/data
    networks:
      - observability
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "cardapiogo", "-U", "cardapiogo" ]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'

  zitadel:
    container_name: flyfood-zitadel
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: postgres
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: cardapiogo
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: cardapiogo
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: cardapiogo
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: cardapiogo
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: cardapiogo
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_TLS_ENABLED: false
      ZITADEL_EXTERNAL_DOMAIN: "192.168.18.5"
      ZITADEL_EXTERNAL_SECURE: "false"
    depends_on:
      postgres:
        condition: 'service_healthy'
    ports:
      - '8080:8080'
    networks:
      - observability
  
  prometheus:
    image: bitnami/prometheus
    container_name: flyfood-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
    networks:
      - observability

  grafana:
    image: grafana/grafana
    container_name: flyfood-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - observability

  localstack:
    container_name: "flyfood-localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_API_KEY}
      - PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack"
      - localstack_data:/var/run/docker.sock"

volumes:
  postgres-data:
  prometheus_data:
  grafana_data:
  localstack_data:

networks:
  observability:
    driver: bridge
