// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OrderStatus string

const (
	OrderStatusCREATED            OrderStatus = "CREATED"
	OrderStatusCANCELLED          OrderStatus = "CANCELLED"
	OrderStatusVERIFIEDBYCUSTOMER OrderStatus = "VERIFIED_BY_CUSTOMER"
	OrderStatusVERIFIEDBYSTORE    OrderStatus = "VERIFIED_BY_STORE"
	OrderStatusINPROCESS          OrderStatus = "IN_PROCESS"
	OrderStatusDISPATCHED         OrderStatus = "DISPATCHED"
	OrderStatusDELIVERED          OrderStatus = "DELIVERED"
	OrderStatusCHARGEBACK         OrderStatus = "CHARGEBACK"
	OrderStatusFINISHED           OrderStatus = "FINISHED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type ProductType string

const (
	ProductTypeFOOD  ProductType = "FOOD"
	ProductTypeWATER ProductType = "WATER"
)

func (e *ProductType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductType(s)
	case string:
		*e = ProductType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductType: %T", src)
	}
	return nil
}

type NullProductType struct {
	ProductType ProductType `json:"product_type"`
	Valid       bool        `json:"valid"` // Valid is true if ProductType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductType) Scan(value interface{}) error {
	if value == nil {
		ns.ProductType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductType), nil
}

type Address struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	AddressLine1 string             `db:"address_line_1" json:"address_line_1"`
	AddressLine2 string             `db:"address_line_2" json:"address_line_2"`
	Neighborhood string             `db:"neighborhood" json:"neighborhood"`
	City         string             `db:"city" json:"city"`
	State        string             `db:"state" json:"state"`
	PostalCode   string             `db:"postal_code" json:"postal_code"`
	Location     interface{}        `db:"location" json:"location"`
	Country      string             `db:"country" json:"country"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Customer struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ExternalID string             `db:"external_id" json:"external_id"`
	Name       string             `db:"name" json:"name"`
	LastName   string             `db:"last_name" json:"last_name"`
	Cpf        pgtype.Text        `db:"cpf" json:"cpf"`
	Email      string             `db:"email" json:"email"`
	Phone      string             `db:"phone" json:"phone"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CustomerAddress struct {
	CustomerID pgtype.UUID `db:"customer_id" json:"customer_id"`
	AddressID  pgtype.UUID `db:"address_id" json:"address_id"`
	IsDefault  bool        `db:"is_default" json:"is_default"`
}

type Order struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	StoreID        pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID     pgtype.UUID        `db:"customer_id" json:"customer_id"`
	AddressID      pgtype.UUID        `db:"address_id" json:"address_id"`
	Status         OrderStatus        `db:"status" json:"status"`
	ShippingAmount int32              `db:"shipping_amount" json:"shipping_amount"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type OrderItem struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	OrderID   pgtype.UUID `db:"order_id" json:"order_id"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	Quantity  int32       `db:"quantity" json:"quantity"`
	Amount    int32       `db:"amount" json:"amount"`
	Details   pgtype.Text `db:"details" json:"details"`
}

type Owner struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SignatureActive bool               `db:"signature_active" json:"signature_active"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type PaymentMethodDomain struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type Product struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	StoreID          pgtype.UUID        `db:"store_id" json:"store_id"`
	Sku              pgtype.Text        `db:"sku" json:"sku"`
	ActiveForSale    bool               `db:"active_for_sale" json:"active_for_sale"`
	PromoActive      bool               `db:"promo_active" json:"promo_active"`
	Type             ProductType        `db:"type" json:"type"`
	Tag              string             `db:"tag" json:"tag"`
	Name             string             `db:"name" json:"name"`
	Description      string             `db:"description" json:"description"`
	StockQuantity    int32              `db:"stock_quantity" json:"stock_quantity"`
	Score            int32              `db:"score" json:"score"`
	ImageUrl         pgtype.Text        `db:"image_url" json:"image_url"`
	Details          []byte             `db:"details" json:"details"`
	Price            int32              `db:"price" json:"price"`
	PromotionalPrice pgtype.Int4        `db:"promotional_price" json:"promotional_price"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Store struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	AddressID    pgtype.UUID        `db:"address_id" json:"address_id"`
	Cnpj         string             `db:"cnpj" json:"cnpj"`
	Name         string             `db:"name" json:"name"`
	Description  pgtype.Text        `db:"description" json:"description"`
	Active       bool               `db:"active" json:"active"`
	Phone        string             `db:"phone" json:"phone"`
	Score        int32              `db:"score" json:"score"`
	IsOpen       bool               `db:"is_open" json:"is_open"`
	Type         int32              `db:"type" json:"type"`
	ProfileImage pgtype.Text        `db:"profile_image" json:"profile_image"`
	HeaderImage  pgtype.Text        `db:"header_image" json:"header_image"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type StoreBusinessHour struct {
	StoreID     pgtype.UUID `db:"store_id" json:"store_id"`
	Weekday     int16       `db:"weekday" json:"weekday"`
	OpenHour    int16       `db:"open_hour" json:"open_hour"`
	ClosingHour int16       `db:"closing_hour" json:"closing_hour"`
}

type StorePaymentMethod struct {
	StoreID       pgtype.UUID `db:"store_id" json:"store_id"`
	PaymentMethod int32       `db:"payment_method" json:"payment_method"`
}

type StoreTypeDomain struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}
