// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAddress = `-- name: DeleteAddress :one
DELETE FROM address
WHERE id = $1
RETURNING id
`

// DeleteAddress
//
//	DELETE FROM address
//	WHERE id = $1
//	RETURNING id
func (q *Queries) DeleteAddress(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAddress, id)
	err := row.Scan(&id)
	return id, err
}

const deleteBusinessHoursNotIn = `-- name: DeleteBusinessHoursNotIn :exec
DELETE FROM store_business_hour
WHERE store_id = $1
  AND weekday != ALL($2::smallint[])
`

type DeleteBusinessHoursNotInParams struct {
	StoreID       pgtype.UUID `db:"store_id" json:"store_id"`
	BusinessHours []int16     `db:"business_hours" json:"business_hours"`
}

// DeleteBusinessHoursNotIn
//
//	DELETE FROM store_business_hour
//	WHERE store_id = $1
//	  AND weekday != ALL($2::smallint[])
func (q *Queries) DeleteBusinessHoursNotIn(ctx context.Context, arg DeleteBusinessHoursNotInParams) error {
	_, err := q.db.Exec(ctx, deleteBusinessHoursNotIn, arg.StoreID, arg.BusinessHours)
	return err
}

const deleteCustomerAddress = `-- name: DeleteCustomerAddress :one
DELETE FROM customer_address
WHERE customer_id = $1 AND address_id = $2
RETURNING customer_id
`

type DeleteCustomerAddressParams struct {
	CustomerID pgtype.UUID `db:"customer_id" json:"customer_id"`
	AddressID  pgtype.UUID `db:"address_id" json:"address_id"`
}

// DeleteCustomerAddress
//
//	DELETE FROM customer_address
//	WHERE customer_id = $1 AND address_id = $2
//	RETURNING customer_id
func (q *Queries) DeleteCustomerAddress(ctx context.Context, arg DeleteCustomerAddressParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCustomerAddress, arg.CustomerID, arg.AddressID)
	var customer_id pgtype.UUID
	err := row.Scan(&customer_id)
	return customer_id, err
}

const deletePaymentMethodsNotIn = `-- name: DeletePaymentMethodsNotIn :exec
DELETE FROM store_payment_method
WHERE store_id = $1
  AND payment_method != ALL($2::int[])
`

type DeletePaymentMethodsNotInParams struct {
	StoreID        pgtype.UUID `db:"store_id" json:"store_id"`
	PaymentMethods []int32     `db:"payment_methods" json:"payment_methods"`
}

// DeletePaymentMethodsNotIn
//
//	DELETE FROM store_payment_method
//	WHERE store_id = $1
//	  AND payment_method != ALL($2::int[])
func (q *Queries) DeletePaymentMethodsNotIn(ctx context.Context, arg DeletePaymentMethodsNotInParams) error {
	_, err := q.db.Exec(ctx, deletePaymentMethodsNotIn, arg.StoreID, arg.PaymentMethods)
	return err
}

const findAddressesByExternalCustomerID = `-- name: FindAddressesByExternalCustomerID :many
SELECT a.id, a.name, ca.is_default, a.address_line_1, a.address_line_2, a.neighborhood, a.city, 
    a.state, a.postal_code, a.country, ST_Y(a.location::geometry)::float8 AS latitude,
    ST_X(a.location::geometry)::float8 AS longitude
FROM address a
LEFT JOIN customer_address ca ON a.id = ca.address_id
LEFT JOIN customer c ON ca.customer_id = c.id
WHERE c.external_id = $1
`

type FindAddressesByExternalCustomerIDRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	IsDefault    pgtype.Bool `db:"is_default" json:"is_default"`
	AddressLine1 string      `db:"address_line_1" json:"address_line_1"`
	AddressLine2 string      `db:"address_line_2" json:"address_line_2"`
	Neighborhood string      `db:"neighborhood" json:"neighborhood"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	PostalCode   string      `db:"postal_code" json:"postal_code"`
	Country      string      `db:"country" json:"country"`
	Latitude     float64     `db:"latitude" json:"latitude"`
	Longitude    float64     `db:"longitude" json:"longitude"`
}

// FindAddressesByExternalCustomerID
//
//	SELECT a.id, a.name, ca.is_default, a.address_line_1, a.address_line_2, a.neighborhood, a.city,
//	    a.state, a.postal_code, a.country, ST_Y(a.location::geometry)::float8 AS latitude,
//	    ST_X(a.location::geometry)::float8 AS longitude
//	FROM address a
//	LEFT JOIN customer_address ca ON a.id = ca.address_id
//	LEFT JOIN customer c ON ca.customer_id = c.id
//	WHERE c.external_id = $1
func (q *Queries) FindAddressesByExternalCustomerID(ctx context.Context, externalID string) ([]FindAddressesByExternalCustomerIDRow, error) {
	rows, err := q.db.Query(ctx, findAddressesByExternalCustomerID, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAddressesByExternalCustomerIDRow
	for rows.Next() {
		var i FindAddressesByExternalCustomerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefault,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Neighborhood,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCustomerByExternalID = `-- name: FindCustomerByExternalID :one
SELECT c.id, c.external_id, c.name, c.last_name, c.cpf, c.email, c.phone
FROM customer c
WHERE c.external_id = $1
LIMIT 1
`

type FindCustomerByExternalIDRow struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	ExternalID string      `db:"external_id" json:"external_id"`
	Name       string      `db:"name" json:"name"`
	LastName   string      `db:"last_name" json:"last_name"`
	Cpf        pgtype.Text `db:"cpf" json:"cpf"`
	Email      string      `db:"email" json:"email"`
	Phone      string      `db:"phone" json:"phone"`
}

// FindCustomerByExternalID
//
//	SELECT c.id, c.external_id, c.name, c.last_name, c.cpf, c.email, c.phone
//	FROM customer c
//	WHERE c.external_id = $1
//	LIMIT 1
func (q *Queries) FindCustomerByExternalID(ctx context.Context, externalID string) (FindCustomerByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, findCustomerByExternalID, externalID)
	var i FindCustomerByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.LastName,
		&i.Cpf,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const findCustomerByID = `-- name: FindCustomerByID :one
SELECT c.id, c.external_id, c.name, c.last_name, c.cpf, c.email, c.phone
FROM customer c
WHERE c.id = $1
LIMIT 1
`

type FindCustomerByIDRow struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	ExternalID string      `db:"external_id" json:"external_id"`
	Name       string      `db:"name" json:"name"`
	LastName   string      `db:"last_name" json:"last_name"`
	Cpf        pgtype.Text `db:"cpf" json:"cpf"`
	Email      string      `db:"email" json:"email"`
	Phone      string      `db:"phone" json:"phone"`
}

// FindCustomerByID
//
//	SELECT c.id, c.external_id, c.name, c.last_name, c.cpf, c.email, c.phone
//	FROM customer c
//	WHERE c.id = $1
//	LIMIT 1
func (q *Queries) FindCustomerByID(ctx context.Context, id pgtype.UUID) (FindCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, findCustomerByID, id)
	var i FindCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.LastName,
		&i.Cpf,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const findOwnerByCustomerExternalID = `-- name: FindOwnerByCustomerExternalID :one
SELECT o.id, o.signature_active, o.created_at, o.updated_at, o.deleted_at
FROM owner o
JOIN customer c ON o.id = c.id
WHERE c.external_id = $1
LIMIT 1
`

// FindOwnerByCustomerExternalID
//
//	SELECT o.id, o.signature_active, o.created_at, o.updated_at, o.deleted_at
//	FROM owner o
//	JOIN customer c ON o.id = c.id
//	WHERE c.external_id = $1
//	LIMIT 1
func (q *Queries) FindOwnerByCustomerExternalID(ctx context.Context, externalID string) (Owner, error) {
	row := q.db.QueryRow(ctx, findOwnerByCustomerExternalID, externalID)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.SignatureActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findOwnerByID = `-- name: FindOwnerByID :one
SELECT o.id, o.signature_active, o.created_at, o.updated_at, o.deleted_at
FROM owner o
WHERE o.id = $1
LIMIT 1
`

// FindOwnerByID
//
//	SELECT o.id, o.signature_active, o.created_at, o.updated_at, o.deleted_at
//	FROM owner o
//	WHERE o.id = $1
//	LIMIT 1
func (q *Queries) FindOwnerByID(ctx context.Context, id pgtype.UUID) (Owner, error) {
	row := q.db.QueryRow(ctx, findOwnerByID, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.SignatureActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findStoreBusinessHoursByStoreId = `-- name: FindStoreBusinessHoursByStoreId :many
SELECT bh.weekday, bh.open_hour, bh.closing_hour
FROM store_business_hour bh
WHERE bh.store_id = $1
ORDER BY bh.weekday
`

type FindStoreBusinessHoursByStoreIdRow struct {
	Weekday     int16 `db:"weekday" json:"weekday"`
	OpenHour    int16 `db:"open_hour" json:"open_hour"`
	ClosingHour int16 `db:"closing_hour" json:"closing_hour"`
}

// FindStoreBusinessHoursByStoreId
//
//	SELECT bh.weekday, bh.open_hour, bh.closing_hour
//	FROM store_business_hour bh
//	WHERE bh.store_id = $1
//	ORDER BY bh.weekday
func (q *Queries) FindStoreBusinessHoursByStoreId(ctx context.Context, storeID pgtype.UUID) ([]FindStoreBusinessHoursByStoreIdRow, error) {
	rows, err := q.db.Query(ctx, findStoreBusinessHoursByStoreId, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindStoreBusinessHoursByStoreIdRow
	for rows.Next() {
		var i FindStoreBusinessHoursByStoreIdRow
		if err := rows.Scan(&i.Weekday, &i.OpenHour, &i.ClosingHour); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findStoreByID = `-- name: FindStoreByID :one
SELECT
    s.id, s.owner_id, s.cnpj, s.name, s.description, s.active, s.phone, s.score, s.is_open,
    s.type, s.profile_image, s.header_image, s.created_at, s.updated_at, s.deleted_at,
    a.address_line_1, a.address_line_2, a.neighborhood, a.city, a.state, a.postal_code, a.country, ST_X(a.location::geometry)::float8 AS latitude,
    ST_Y(a.location::geometry)::float8 AS longitude
FROM store s
LEFT JOIN address a               ON a.id = s.address_id
LEFT JOIN store_business_hour bh  ON bh.store_id = s.id
LEFT JOIN store_payment_method pm ON pm.store_id = s.id
LEFT JOIN product p               ON p.store_id = s.id
WHERE s.id = $1
GROUP BY
    s.id, s.owner_id, s.cnpj, s.name, s.description, s.active, s.phone, s.score, s.is_open,
    s.type, s.profile_image, s.header_image, s.created_at, s.updated_at, s.deleted_at,
    a.address_line_1, a.address_line_2, a.neighborhood, a.city, a.state, a.postal_code, a.country, latitude, longitude
`

type FindStoreByIDRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Cnpj         string             `db:"cnpj" json:"cnpj"`
	Name         string             `db:"name" json:"name"`
	Description  pgtype.Text        `db:"description" json:"description"`
	Active       bool               `db:"active" json:"active"`
	Phone        string             `db:"phone" json:"phone"`
	Score        int32              `db:"score" json:"score"`
	IsOpen       bool               `db:"is_open" json:"is_open"`
	Type         int32              `db:"type" json:"type"`
	ProfileImage pgtype.Text        `db:"profile_image" json:"profile_image"`
	HeaderImage  pgtype.Text        `db:"header_image" json:"header_image"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	AddressLine1 pgtype.Text        `db:"address_line_1" json:"address_line_1"`
	AddressLine2 pgtype.Text        `db:"address_line_2" json:"address_line_2"`
	Neighborhood pgtype.Text        `db:"neighborhood" json:"neighborhood"`
	City         pgtype.Text        `db:"city" json:"city"`
	State        pgtype.Text        `db:"state" json:"state"`
	PostalCode   pgtype.Text        `db:"postal_code" json:"postal_code"`
	Country      pgtype.Text        `db:"country" json:"country"`
	Latitude     float64            `db:"latitude" json:"latitude"`
	Longitude    float64            `db:"longitude" json:"longitude"`
}

// FindStoreByID
//
//	SELECT
//	    s.id, s.owner_id, s.cnpj, s.name, s.description, s.active, s.phone, s.score, s.is_open,
//	    s.type, s.profile_image, s.header_image, s.created_at, s.updated_at, s.deleted_at,
//	    a.address_line_1, a.address_line_2, a.neighborhood, a.city, a.state, a.postal_code, a.country, ST_X(a.location::geometry)::float8 AS latitude,
//	    ST_Y(a.location::geometry)::float8 AS longitude
//	FROM store s
//	LEFT JOIN address a               ON a.id = s.address_id
//	LEFT JOIN store_business_hour bh  ON bh.store_id = s.id
//	LEFT JOIN store_payment_method pm ON pm.store_id = s.id
//	LEFT JOIN product p               ON p.store_id = s.id
//	WHERE s.id = $1
//	GROUP BY
//	    s.id, s.owner_id, s.cnpj, s.name, s.description, s.active, s.phone, s.score, s.is_open,
//	    s.type, s.profile_image, s.header_image, s.created_at, s.updated_at, s.deleted_at,
//	    a.address_line_1, a.address_line_2, a.neighborhood, a.city, a.state, a.postal_code, a.country, latitude, longitude
func (q *Queries) FindStoreByID(ctx context.Context, id pgtype.UUID) (FindStoreByIDRow, error) {
	row := q.db.QueryRow(ctx, findStoreByID, id)
	var i FindStoreByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Cnpj,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.Phone,
		&i.Score,
		&i.IsOpen,
		&i.Type,
		&i.ProfileImage,
		&i.HeaderImage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const findStorePaymentMethodsByStoreId = `-- name: FindStorePaymentMethodsByStoreId :many
SELECT pm.payment_method
FROM store_payment_method pm
WHERE pm.store_id = $1
ORDER BY pm.payment_method
`

// FindStorePaymentMethodsByStoreId
//
//	SELECT pm.payment_method
//	FROM store_payment_method pm
//	WHERE pm.store_id = $1
//	ORDER BY pm.payment_method
func (q *Queries) FindStorePaymentMethodsByStoreId(ctx context.Context, storeID pgtype.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, findStorePaymentMethodsByStoreId, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var payment_method int32
		if err := rows.Scan(&payment_method); err != nil {
			return nil, err
		}
		items = append(items, payment_method)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAddress = `-- name: SaveAddress :exec
INSERT INTO address (id, name, address_line_1, address_line_2, neighborhood, 
    city, state, postal_code, country, location, created_at, updated_at, deleted_at)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    ST_SetSRID(ST_MakePoint($10::float8, $11::float8), 4326)::geography,
    NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL
)
ON CONFLICT (id) DO UPDATE
    SET
        name          = EXCLUDED.name,
        address_line_1 = EXCLUDED.address_line_1,
        address_line_2 = EXCLUDED.address_line_2,
        neighborhood  = EXCLUDED.neighborhood,
        city          = EXCLUDED.city,
        state         = EXCLUDED.state,
        postal_code   = EXCLUDED.postal_code,
        country       = EXCLUDED.country,
        location      = EXCLUDED.location,
        updated_at    = NOW() AT TIME ZONE 'UTC'
`

type SaveAddressParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	AddressLine1 string      `db:"address_line_1" json:"address_line_1"`
	AddressLine2 string      `db:"address_line_2" json:"address_line_2"`
	Neighborhood string      `db:"neighborhood" json:"neighborhood"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	PostalCode   string      `db:"postal_code" json:"postal_code"`
	Country      string      `db:"country" json:"country"`
	Latitude     float64     `db:"latitude" json:"latitude"`
	Longitude    float64     `db:"longitude" json:"longitude"`
}

// SaveAddress
//
//	INSERT INTO address (id, name, address_line_1, address_line_2, neighborhood,
//	    city, state, postal_code, country, location, created_at, updated_at, deleted_at)
//	VALUES (
//	    $1, $2, $3, $4, $5, $6, $7, $8, $9,
//	    ST_SetSRID(ST_MakePoint($10::float8, $11::float8), 4326)::geography,
//	    NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL
//	)
//	ON CONFLICT (id) DO UPDATE
//	    SET
//	        name          = EXCLUDED.name,
//	        address_line_1 = EXCLUDED.address_line_1,
//	        address_line_2 = EXCLUDED.address_line_2,
//	        neighborhood  = EXCLUDED.neighborhood,
//	        city          = EXCLUDED.city,
//	        state         = EXCLUDED.state,
//	        postal_code   = EXCLUDED.postal_code,
//	        country       = EXCLUDED.country,
//	        location      = EXCLUDED.location,
//	        updated_at    = NOW() AT TIME ZONE 'UTC'
func (q *Queries) SaveAddress(ctx context.Context, arg SaveAddressParams) error {
	_, err := q.db.Exec(ctx, saveAddress,
		arg.ID,
		arg.Name,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
	)
	return err
}

const saveCustomer = `-- name: SaveCustomer :exec
INSERT INTO customer (id, external_id, name, last_name, cpf, email, phone, created_at, updated_at)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, 
    NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    last_name = EXCLUDED.last_name,
    cpf = EXCLUDED.cpf,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    updated_at = NOW() AT TIME ZONE 'UTC'
`

type SaveCustomerParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	ExternalID string      `db:"external_id" json:"external_id"`
	Name       string      `db:"name" json:"name"`
	LastName   string      `db:"last_name" json:"last_name"`
	Cpf        pgtype.Text `db:"cpf" json:"cpf"`
	Email      string      `db:"email" json:"email"`
	Phone      string      `db:"phone" json:"phone"`
}

// SaveCustomer
//
//	INSERT INTO customer (id, external_id, name, last_name, cpf, email, phone, created_at, updated_at)
//	VALUES (
//	    $1, $2, $3, $4, $5, $6, $7,
//	    NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'
//	)
//	ON CONFLICT (id) DO UPDATE SET
//	    name = EXCLUDED.name,
//	    last_name = EXCLUDED.last_name,
//	    cpf = EXCLUDED.cpf,
//	    email = EXCLUDED.email,
//	    phone = EXCLUDED.phone,
//	    updated_at = NOW() AT TIME ZONE 'UTC'
func (q *Queries) SaveCustomer(ctx context.Context, arg SaveCustomerParams) error {
	_, err := q.db.Exec(ctx, saveCustomer,
		arg.ID,
		arg.ExternalID,
		arg.Name,
		arg.LastName,
		arg.Cpf,
		arg.Email,
		arg.Phone,
	)
	return err
}

const saveCustomerAddress = `-- name: SaveCustomerAddress :exec
INSERT INTO customer_address (customer_id, address_id, is_default)
VALUES ($1, $2, $3)
`

type SaveCustomerAddressParams struct {
	CustomerID pgtype.UUID `db:"customer_id" json:"customer_id"`
	AddressID  pgtype.UUID `db:"address_id" json:"address_id"`
	IsDefault  bool        `db:"is_default" json:"is_default"`
}

// SaveCustomerAddress
//
//	INSERT INTO customer_address (customer_id, address_id, is_default)
//	VALUES ($1, $2, $3)
func (q *Queries) SaveCustomerAddress(ctx context.Context, arg SaveCustomerAddressParams) error {
	_, err := q.db.Exec(ctx, saveCustomerAddress, arg.CustomerID, arg.AddressID, arg.IsDefault)
	return err
}

const saveOwner = `-- name: SaveOwner :exec
INSERT INTO owner (id, signature_active, created_at, updated_at)
VALUES (
    $1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'
)
ON CONFLICT (id) DO UPDATE SET
    signature_active = EXCLUDED.signature_active,
    updated_at = NOW() AT TIME ZONE 'UTC'
`

type SaveOwnerParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	SignatureActive bool        `db:"signature_active" json:"signature_active"`
}

// SaveOwner
//
//	INSERT INTO owner (id, signature_active, created_at, updated_at)
//	VALUES (
//	    $1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'
//	)
//	ON CONFLICT (id) DO UPDATE SET
//	    signature_active = EXCLUDED.signature_active,
//	    updated_at = NOW() AT TIME ZONE 'UTC'
func (q *Queries) SaveOwner(ctx context.Context, arg SaveOwnerParams) error {
	_, err := q.db.Exec(ctx, saveOwner, arg.ID, arg.SignatureActive)
	return err
}

const saveStore = `-- name: SaveStore :exec
INSERT INTO store (id, owner_id, address_id, cnpj, name, description, active, is_open, phone, 
    score, type, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
ON CONFLICT (id) DO UPDATE
    SET
        owner_id = EXCLUDED.owner_id,
        address_id = EXCLUDED.address_id,
        cnpj = EXCLUDED.cnpj,
        name = EXCLUDED.name,
        description = EXCLUDED.description,
        active = EXCLUDED.active,
        is_open = EXCLUDED.is_open,
        phone = EXCLUDED.phone,
        score = EXCLUDED.score,
        type = EXCLUDED.type,
        updated_at = NOW() AT TIME ZONE 'UTC'
`

type SaveStoreParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	OwnerID     pgtype.UUID `db:"owner_id" json:"owner_id"`
	AddressID   pgtype.UUID `db:"address_id" json:"address_id"`
	Cnpj        string      `db:"cnpj" json:"cnpj"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	Active      bool        `db:"active" json:"active"`
	IsOpen      bool        `db:"is_open" json:"is_open"`
	Phone       string      `db:"phone" json:"phone"`
	Score       int32       `db:"score" json:"score"`
	Type        int32       `db:"type" json:"type"`
}

// SaveStore
//
//	INSERT INTO store (id, owner_id, address_id, cnpj, name, description, active, is_open, phone,
//	    score, type, created_at, updated_at, deleted_at)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
//	ON CONFLICT (id) DO UPDATE
//	    SET
//	        owner_id = EXCLUDED.owner_id,
//	        address_id = EXCLUDED.address_id,
//	        cnpj = EXCLUDED.cnpj,
//	        name = EXCLUDED.name,
//	        description = EXCLUDED.description,
//	        active = EXCLUDED.active,
//	        is_open = EXCLUDED.is_open,
//	        phone = EXCLUDED.phone,
//	        score = EXCLUDED.score,
//	        type = EXCLUDED.type,
//	        updated_at = NOW() AT TIME ZONE 'UTC'
func (q *Queries) SaveStore(ctx context.Context, arg SaveStoreParams) error {
	_, err := q.db.Exec(ctx, saveStore,
		arg.ID,
		arg.OwnerID,
		arg.AddressID,
		arg.Cnpj,
		arg.Name,
		arg.Description,
		arg.Active,
		arg.IsOpen,
		arg.Phone,
		arg.Score,
		arg.Type,
	)
	return err
}

const upsertBusinessHour = `-- name: UpsertBusinessHour :exec
INSERT INTO store_business_hour (store_id, weekday, open_hour, closing_hour)
VALUES ($1, $2, $3, $4)
ON CONFLICT (store_id, weekday) DO UPDATE SET
    open_hour    = EXCLUDED.open_hour,
    closing_hour = EXCLUDED.closing_hour
`

type UpsertBusinessHourParams struct {
	StoreID     pgtype.UUID `db:"store_id" json:"store_id"`
	Weekday     int16       `db:"weekday" json:"weekday"`
	OpenHour    int16       `db:"open_hour" json:"open_hour"`
	ClosingHour int16       `db:"closing_hour" json:"closing_hour"`
}

// UpsertBusinessHour
//
//	INSERT INTO store_business_hour (store_id, weekday, open_hour, closing_hour)
//	VALUES ($1, $2, $3, $4)
//	ON CONFLICT (store_id, weekday) DO UPDATE SET
//	    open_hour    = EXCLUDED.open_hour,
//	    closing_hour = EXCLUDED.closing_hour
func (q *Queries) UpsertBusinessHour(ctx context.Context, arg UpsertBusinessHourParams) error {
	_, err := q.db.Exec(ctx, upsertBusinessHour,
		arg.StoreID,
		arg.Weekday,
		arg.OpenHour,
		arg.ClosingHour,
	)
	return err
}

const upsertPaymentMethod = `-- name: UpsertPaymentMethod :exec
INSERT INTO store_payment_method (store_id, payment_method)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type UpsertPaymentMethodParams struct {
	StoreID       pgtype.UUID `db:"store_id" json:"store_id"`
	PaymentMethod int32       `db:"payment_method" json:"payment_method"`
}

// UpsertPaymentMethod
//
//	INSERT INTO store_payment_method (store_id, payment_method)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) UpsertPaymentMethod(ctx context.Context, arg UpsertPaymentMethodParams) error {
	_, err := q.db.Exec(ctx, upsertPaymentMethod, arg.StoreID, arg.PaymentMethod)
	return err
}
