// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: batch.go

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const addNewCustomerAddresses = `-- name: AddNewCustomerAddresses :batchexec
INSERT INTO address (customer_id, name, address_line_1, address_line_2, neighborhood, city, state,
postal_code, latitude, longitude, country, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
`

type AddNewCustomerAddressesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddNewCustomerAddressesParams struct {
	CustomerID   string      `db:"customer_id" json:"customer_id"`
	Name         string      `db:"name" json:"name"`
	AddressLine1 string      `db:"address_line_1" json:"address_line_1"`
	AddressLine2 string      `db:"address_line_2" json:"address_line_2"`
	Neighborhood string      `db:"neighborhood" json:"neighborhood"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	PostalCode   string      `db:"postal_code" json:"postal_code"`
	Latitude     pgtype.Text `db:"latitude" json:"latitude"`
	Longitude    pgtype.Text `db:"longitude" json:"longitude"`
	Country      string      `db:"country" json:"country"`
}

// AddNewCustomerAddresses
//
//	INSERT INTO address (customer_id, name, address_line_1, address_line_2, neighborhood, city, state,
//	postal_code, latitude, longitude, country, created_at, updated_at, deleted_at)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
//	        $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
func (q *Queries) AddNewCustomerAddresses(ctx context.Context, arg []AddNewCustomerAddressesParams) *AddNewCustomerAddressesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.CustomerID,
			a.Name,
			a.AddressLine1,
			a.AddressLine2,
			a.Neighborhood,
			a.City,
			a.State,
			a.PostalCode,
			a.Latitude,
			a.Longitude,
			a.Country,
		}
		batch.Queue(addNewCustomerAddresses, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddNewCustomerAddressesBatchResults{br, len(arg), false}
}

func (b *AddNewCustomerAddressesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddNewCustomerAddressesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteCustomerAddresses = `-- name: DeleteCustomerAddresses :batchexec
DELETE FROM address
WHERE customer_id = $1
    AND name = $2
    AND address_line_1 = $3
    AND address_line_2 = $4
    AND neighborhood = $5
    AND city = $6
  And state = $7
    AND postal_code = $8
    AND country = $9
`

type DeleteCustomerAddressesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type DeleteCustomerAddressesParams struct {
	CustomerID   string `db:"customer_id" json:"customer_id"`
	Name         string `db:"name" json:"name"`
	AddressLine1 string `db:"address_line_1" json:"address_line_1"`
	AddressLine2 string `db:"address_line_2" json:"address_line_2"`
	Neighborhood string `db:"neighborhood" json:"neighborhood"`
	City         string `db:"city" json:"city"`
	State        string `db:"state" json:"state"`
	PostalCode   string `db:"postal_code" json:"postal_code"`
	Country      string `db:"country" json:"country"`
}

// DeleteCustomerAddresses
//
//	DELETE FROM address
//	WHERE customer_id = $1
//	    AND name = $2
//	    AND address_line_1 = $3
//	    AND address_line_2 = $4
//	    AND neighborhood = $5
//	    AND city = $6
//	  And state = $7
//	    AND postal_code = $8
//	    AND country = $9
func (q *Queries) DeleteCustomerAddresses(ctx context.Context, arg []DeleteCustomerAddressesParams) *DeleteCustomerAddressesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.CustomerID,
			a.Name,
			a.AddressLine1,
			a.AddressLine2,
			a.Neighborhood,
			a.City,
			a.State,
			a.PostalCode,
			a.Country,
		}
		batch.Queue(deleteCustomerAddresses, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteCustomerAddressesBatchResults{br, len(arg), false}
}

func (b *DeleteCustomerAddressesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteCustomerAddressesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteStoreBusinessHour = `-- name: DeleteStoreBusinessHour :batchexec
DELETE FROM store_business_hour bh
WHERE bh.id = $1
AND bh.weekday = $2
AND bh.open_hour = $3
AND bh.closing_hour = $4
`

type DeleteStoreBusinessHourBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type DeleteStoreBusinessHourParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Weekday     int32       `db:"weekday" json:"weekday"`
	OpenHour    string      `db:"open_hour" json:"open_hour"`
	ClosingHour string      `db:"closing_hour" json:"closing_hour"`
}

// DeleteStoreBusinessHour
//
//	DELETE FROM store_business_hour bh
//	WHERE bh.id = $1
//	AND bh.weekday = $2
//	AND bh.open_hour = $3
//	AND bh.closing_hour = $4
func (q *Queries) DeleteStoreBusinessHour(ctx context.Context, arg []DeleteStoreBusinessHourParams) *DeleteStoreBusinessHourBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Weekday,
			a.OpenHour,
			a.ClosingHour,
		}
		batch.Queue(deleteStoreBusinessHour, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteStoreBusinessHourBatchResults{br, len(arg), false}
}

func (b *DeleteStoreBusinessHourBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteStoreBusinessHourBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteStorePaymentMethods = `-- name: DeleteStorePaymentMethods :batchexec
DELETE FROM store_payment_method
WHERE id = $1 AND payment_method = $2
`

type DeleteStorePaymentMethodsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type DeleteStorePaymentMethodsParams struct {
	ID            pgtype.UUID   `db:"id" json:"id"`
	PaymentMethod PaymentMethod `db:"payment_method" json:"payment_method"`
}

// DeleteStorePaymentMethods
//
//	DELETE FROM store_payment_method
//	WHERE id = $1 AND payment_method = $2
func (q *Queries) DeleteStorePaymentMethods(ctx context.Context, arg []DeleteStorePaymentMethodsParams) *DeleteStorePaymentMethodsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.PaymentMethod,
		}
		batch.Queue(deleteStorePaymentMethods, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteStorePaymentMethodsBatchResults{br, len(arg), false}
}

func (b *DeleteStorePaymentMethodsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteStorePaymentMethodsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const saveStoreBusinessHour = `-- name: SaveStoreBusinessHour :batchexec
INSERT INTO store_business_hour(id, weekday, open_hour, closing_hour)
VALUES ($1, $2, $3, $4)
`

type SaveStoreBusinessHourBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type SaveStoreBusinessHourParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Weekday     int32       `db:"weekday" json:"weekday"`
	OpenHour    string      `db:"open_hour" json:"open_hour"`
	ClosingHour string      `db:"closing_hour" json:"closing_hour"`
}

// SaveStoreBusinessHour
//
//	INSERT INTO store_business_hour(id, weekday, open_hour, closing_hour)
//	VALUES ($1, $2, $3, $4)
func (q *Queries) SaveStoreBusinessHour(ctx context.Context, arg []SaveStoreBusinessHourParams) *SaveStoreBusinessHourBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Weekday,
			a.OpenHour,
			a.ClosingHour,
		}
		batch.Queue(saveStoreBusinessHour, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &SaveStoreBusinessHourBatchResults{br, len(arg), false}
}

func (b *SaveStoreBusinessHourBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *SaveStoreBusinessHourBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const saveStorePaymentMethods = `-- name: SaveStorePaymentMethods :batchexec
INSERT INTO store_payment_method (id, payment_method)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SaveStorePaymentMethodsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type SaveStorePaymentMethodsParams struct {
	ID            pgtype.UUID   `db:"id" json:"id"`
	PaymentMethod PaymentMethod `db:"payment_method" json:"payment_method"`
}

// SaveStorePaymentMethods
//
//	INSERT INTO store_payment_method (id, payment_method)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) SaveStorePaymentMethods(ctx context.Context, arg []SaveStorePaymentMethodsParams) *SaveStorePaymentMethodsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.PaymentMethod,
		}
		batch.Queue(saveStorePaymentMethods, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &SaveStorePaymentMethodsBatchResults{br, len(arg), false}
}

func (b *SaveStorePaymentMethodsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *SaveStorePaymentMethodsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
