// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAddressesByCustomerID = `-- name: FindAddressesByCustomerID :many
SELECT a.id, a.name, a.address_line_1, address_line_2, a.neighborhood, a.city, a.state, a.postal_code, a.country, a.latitude, a.longitude
FROM address a
WHERE a.customer_id = $1
ORDER BY a.created_at DESC
`

type FindAddressesByCustomerIDRow struct {
	ID           int64       `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	AddressLine1 string      `db:"address_line_1" json:"address_line_1"`
	AddressLine2 string      `db:"address_line_2" json:"address_line_2"`
	Neighborhood string      `db:"neighborhood" json:"neighborhood"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	PostalCode   string      `db:"postal_code" json:"postal_code"`
	Country      string      `db:"country" json:"country"`
	Latitude     pgtype.Text `db:"latitude" json:"latitude"`
	Longitude    pgtype.Text `db:"longitude" json:"longitude"`
}

// FindAddressesByCustomerID
//
//	SELECT a.id, a.name, a.address_line_1, address_line_2, a.neighborhood, a.city, a.state, a.postal_code, a.country, a.latitude, a.longitude
//	FROM address a
//	WHERE a.customer_id = $1
//	ORDER BY a.created_at DESC
func (q *Queries) FindAddressesByCustomerID(ctx context.Context, customerID string) ([]FindAddressesByCustomerIDRow, error) {
	rows, err := q.db.Query(ctx, findAddressesByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAddressesByCustomerIDRow
	for rows.Next() {
		var i FindAddressesByCustomerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Neighborhood,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findBusinessHourByStoreID = `-- name: FindBusinessHourByStoreID :many
SELECT bh.weekday, bh.open_hour, bh.closing_hour
FROM store_business_hour bh
WHERE bh.id = $1
`

type FindBusinessHourByStoreIDRow struct {
	Weekday     int32  `db:"weekday" json:"weekday"`
	OpenHour    string `db:"open_hour" json:"open_hour"`
	ClosingHour string `db:"closing_hour" json:"closing_hour"`
}

// FindBusinessHourByStoreID
//
//	SELECT bh.weekday, bh.open_hour, bh.closing_hour
//	FROM store_business_hour bh
//	WHERE bh.id = $1
func (q *Queries) FindBusinessHourByStoreID(ctx context.Context, id pgtype.UUID) ([]FindBusinessHourByStoreIDRow, error) {
	rows, err := q.db.Query(ctx, findBusinessHourByStoreID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindBusinessHourByStoreIDRow
	for rows.Next() {
		var i FindBusinessHourByStoreIDRow
		if err := rows.Scan(&i.Weekday, &i.OpenHour, &i.ClosingHour); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCustomerByID = `-- name: FindCustomerByID :one
SELECT c.id, c.name, c.last_name, c.cpf, c.email, c.phone
FROM customer c
WHERE c.id = $1
LIMIT 1
`

type FindCustomerByIDRow struct {
	ID       string      `db:"id" json:"id"`
	Name     string      `db:"name" json:"name"`
	LastName string      `db:"last_name" json:"last_name"`
	Cpf      pgtype.Text `db:"cpf" json:"cpf"`
	Email    string      `db:"email" json:"email"`
	Phone    string      `db:"phone" json:"phone"`
}

// FindCustomerByID
//
//	SELECT c.id, c.name, c.last_name, c.cpf, c.email, c.phone
//	FROM customer c
//	WHERE c.id = $1
//	LIMIT 1
func (q *Queries) FindCustomerByID(ctx context.Context, id string) (FindCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, findCustomerByID, id)
	var i FindCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Cpf,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const findOwnerByID = `-- name: FindOwnerByID :one
SELECT o.id,
       signature_active,
       COALESCE(
                       ARRAY_AGG(DISTINCT s.id::uuid) FILTER (WHERE s.id IS NOT NULL),
                       '{}'::uuid[]
       )::uuid[] AS store_ids
FROM owner o
         LEFT JOIN store s ON o.id = s.owner_id
WHERE o.id = $1
GROUP BY o.id, signature_active
`

type FindOwnerByIDRow struct {
	ID              string        `db:"id" json:"id"`
	SignatureActive bool          `db:"signature_active" json:"signature_active"`
	StoreIds        []pgtype.UUID `db:"store_ids" json:"store_ids"`
}

// FindOwnerByID
//
//	SELECT o.id,
//	       signature_active,
//	       COALESCE(
//	                       ARRAY_AGG(DISTINCT s.id::uuid) FILTER (WHERE s.id IS NOT NULL),
//	                       '{}'::uuid[]
//	       )::uuid[] AS store_ids
//	FROM owner o
//	         LEFT JOIN store s ON o.id = s.owner_id
//	WHERE o.id = $1
//	GROUP BY o.id, signature_active
func (q *Queries) FindOwnerByID(ctx context.Context, id string) (FindOwnerByIDRow, error) {
	row := q.db.QueryRow(ctx, findOwnerByID, id)
	var i FindOwnerByIDRow
	err := row.Scan(&i.ID, &i.SignatureActive, &i.StoreIds)
	return i, err
}

const findOwnerStores = `-- name: FindOwnerStores :many
SELECT id, name, active, type, delivery_time, score, is_open, profile_image, city, state, country
FROM store
WHERE owner_id = $1
`

type FindOwnerStoresRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Active       bool        `db:"active" json:"active"`
	Type         StoreType   `db:"type" json:"type"`
	DeliveryTime pgtype.Int4 `db:"delivery_time" json:"delivery_time"`
	Score        int32       `db:"score" json:"score"`
	IsOpen       bool        `db:"is_open" json:"is_open"`
	ProfileImage pgtype.Text `db:"profile_image" json:"profile_image"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	Country      string      `db:"country" json:"country"`
}

// FindOwnerStores
//
//	SELECT id, name, active, type, delivery_time, score, is_open, profile_image, city, state, country
//	FROM store
//	WHERE owner_id = $1
func (q *Queries) FindOwnerStores(ctx context.Context, ownerID string) ([]FindOwnerStoresRow, error) {
	rows, err := q.db.Query(ctx, findOwnerStores, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindOwnerStoresRow
	for rows.Next() {
		var i FindOwnerStoresRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.Type,
			&i.DeliveryTime,
			&i.Score,
			&i.IsOpen,
			&i.ProfileImage,
			&i.City,
			&i.State,
			&i.Country,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPaymentMethodsByStoreID = `-- name: FindPaymentMethodsByStoreID :many
SELECT pm.payment_method FROM store_payment_method pm
WHERE id = $1
`

// FindPaymentMethodsByStoreID
//
//	SELECT pm.payment_method FROM store_payment_method pm
//	WHERE id = $1
func (q *Queries) FindPaymentMethodsByStoreID(ctx context.Context, id pgtype.UUID) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, findPaymentMethodsByStoreID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var payment_method PaymentMethod
		if err := rows.Scan(&payment_method); err != nil {
			return nil, err
		}
		items = append(items, payment_method)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProductByID = `-- name: FindProductByID :one
SELECT i.store_id, i.sku, i.active_for_sale, i.promo_active, i.type, i.tag, i.name,
       i.description, i.stock_quantity, i.score, i.image_url, i.details, i.price, i.promotional_price
FROM product i
WHERE i.id = $1
LIMIT 1
`

type FindProductByIDRow struct {
	StoreID          pgtype.UUID `db:"store_id" json:"store_id"`
	Sku              pgtype.Text `db:"sku" json:"sku"`
	ActiveForSale    bool        `db:"active_for_sale" json:"active_for_sale"`
	PromoActive      bool        `db:"promo_active" json:"promo_active"`
	Type             ProductType `db:"type" json:"type"`
	Tag              string      `db:"tag" json:"tag"`
	Name             string      `db:"name" json:"name"`
	Description      string      `db:"description" json:"description"`
	StockQuantity    int32       `db:"stock_quantity" json:"stock_quantity"`
	Score            int32       `db:"score" json:"score"`
	ImageUrl         pgtype.Text `db:"image_url" json:"image_url"`
	Details          []byte      `db:"details" json:"details"`
	Price            int32       `db:"price" json:"price"`
	PromotionalPrice pgtype.Int4 `db:"promotional_price" json:"promotional_price"`
}

// FindProductByID
//
//	SELECT i.store_id, i.sku, i.active_for_sale, i.promo_active, i.type, i.tag, i.name,
//	       i.description, i.stock_quantity, i.score, i.image_url, i.details, i.price, i.promotional_price
//	FROM product i
//	WHERE i.id = $1
//	LIMIT 1
func (q *Queries) FindProductByID(ctx context.Context, id pgtype.UUID) (FindProductByIDRow, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i FindProductByIDRow
	err := row.Scan(
		&i.StoreID,
		&i.Sku,
		&i.ActiveForSale,
		&i.PromoActive,
		&i.Type,
		&i.Tag,
		&i.Name,
		&i.Description,
		&i.StockQuantity,
		&i.Score,
		&i.ImageUrl,
		&i.Details,
		&i.Price,
		&i.PromotionalPrice,
	)
	return i, err
}

const findProductsByStoreID = `-- name: FindProductsByStoreID :many
SELECT i.id, i.store_id, i.sku, i.active_for_sale, i.promo_active, i.type, i.tag, i.name,
       i.description, i.stock_quantity, i.score, i.image_url, i.details, i.price, i.promotional_price
FROM product i
WHERE i.store_id = $1
`

type FindProductsByStoreIDRow struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	StoreID          pgtype.UUID `db:"store_id" json:"store_id"`
	Sku              pgtype.Text `db:"sku" json:"sku"`
	ActiveForSale    bool        `db:"active_for_sale" json:"active_for_sale"`
	PromoActive      bool        `db:"promo_active" json:"promo_active"`
	Type             ProductType `db:"type" json:"type"`
	Tag              string      `db:"tag" json:"tag"`
	Name             string      `db:"name" json:"name"`
	Description      string      `db:"description" json:"description"`
	StockQuantity    int32       `db:"stock_quantity" json:"stock_quantity"`
	Score            int32       `db:"score" json:"score"`
	ImageUrl         pgtype.Text `db:"image_url" json:"image_url"`
	Details          []byte      `db:"details" json:"details"`
	Price            int32       `db:"price" json:"price"`
	PromotionalPrice pgtype.Int4 `db:"promotional_price" json:"promotional_price"`
}

// FindProductsByStoreID
//
//	SELECT i.id, i.store_id, i.sku, i.active_for_sale, i.promo_active, i.type, i.tag, i.name,
//	       i.description, i.stock_quantity, i.score, i.image_url, i.details, i.price, i.promotional_price
//	FROM product i
//	WHERE i.store_id = $1
func (q *Queries) FindProductsByStoreID(ctx context.Context, storeID pgtype.UUID) ([]FindProductsByStoreIDRow, error) {
	rows, err := q.db.Query(ctx, findProductsByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindProductsByStoreIDRow
	for rows.Next() {
		var i FindProductsByStoreIDRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Sku,
			&i.ActiveForSale,
			&i.PromoActive,
			&i.Type,
			&i.Tag,
			&i.Name,
			&i.Description,
			&i.StockQuantity,
			&i.Score,
			&i.ImageUrl,
			&i.Details,
			&i.Price,
			&i.PromotionalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProductsIDByStoreID = `-- name: FindProductsIDByStoreID :many
SELECT p.id from product p
WHERE p.store_id = $1
`

// FindProductsIDByStoreID
//
//	SELECT p.id from product p
//	WHERE p.store_id = $1
func (q *Queries) FindProductsIDByStoreID(ctx context.Context, storeID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, findProductsIDByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findStoreByID = `-- name: FindStoreByID :one
WITH relevant_business_hours AS (
    SELECT id, weekday, open_hour, closing_hour
    FROM store_business_hour bh
    WHERE id = $1
),
     relevant_payment_methods AS (
         SELECT id, payment_method
         FROM store_payment_method pm
         WHERE id = $1
     ),
    relevant_products AS (
        SELECT id, store_id
        FROM product
        WHERE store_id = $1
    )
SELECT
    s.owner_id, s.cnpj, s.name, s.description,
    s.active, s.phone, s.score, s.is_open, s.type, s.delivery_time, s.profile_image,
    s.header_image, s.address_line_1, s.address_line_2, s.neighborhood,
    s.city, s.state, s.postal_code, s.latitude, s.longitude,
    s.country, s.created_at, s.updated_at, s.deleted_at,
    COALESCE(
        ARRAY_AGG(DISTINCT rbh.weekday || ' ' || rbh.open_hour || ' ' || rbh.closing_hour) FILTER (WHERE rbh.id IS NOT NULL),
                    '{}'::text[]
    )::text[] AS business_hours,
    COALESCE(
        ARRAY_AGG(DISTINCT rpm.payment_method) FILTER (WHERE rpm.id IS NOT NULL),
                    '{}'::"PaymentMethod"[]
    )::text[] AS payment_methods,
    COALESCE(
            ARRAY_AGG(DISTINCT rp.id) FILTER (WHERE rp.id IS NOT NULL),
                        '{}'::uuid[]
        )::uuid[] AS products
FROM store s
         LEFT JOIN relevant_business_hours rbh ON s.id = rbh.id
         LEFT JOIN relevant_payment_methods rpm ON s.id = rpm.id
         LEFT JOIN relevant_products rp ON s.id = rp.store_id
WHERE s.id = $1
GROUP BY
    s.owner_id, s.cnpj, s.name, s.description,
    s.active, s.phone, s.score, s.is_open, s.type, s.delivery_time, s.profile_image,
    s.header_image, s.address_line_1, s.address_line_2, s.neighborhood,
    s.city, s.state, s.postal_code, s.latitude, s.longitude,
    s.country, s.created_at, s.updated_at, s.deleted_at
`

type FindStoreByIDRow struct {
	OwnerID        string           `db:"owner_id" json:"owner_id"`
	Cnpj           string           `db:"cnpj" json:"cnpj"`
	Name           string           `db:"name" json:"name"`
	Description    string           `db:"description" json:"description"`
	Active         bool             `db:"active" json:"active"`
	Phone          string           `db:"phone" json:"phone"`
	Score          int32            `db:"score" json:"score"`
	IsOpen         bool             `db:"is_open" json:"is_open"`
	Type           StoreType        `db:"type" json:"type"`
	DeliveryTime   pgtype.Int4      `db:"delivery_time" json:"delivery_time"`
	ProfileImage   pgtype.Text      `db:"profile_image" json:"profile_image"`
	HeaderImage    pgtype.Text      `db:"header_image" json:"header_image"`
	AddressLine1   string           `db:"address_line_1" json:"address_line_1"`
	AddressLine2   string           `db:"address_line_2" json:"address_line_2"`
	Neighborhood   string           `db:"neighborhood" json:"neighborhood"`
	City           string           `db:"city" json:"city"`
	State          string           `db:"state" json:"state"`
	PostalCode     string           `db:"postal_code" json:"postal_code"`
	Latitude       pgtype.Text      `db:"latitude" json:"latitude"`
	Longitude      pgtype.Text      `db:"longitude" json:"longitude"`
	Country        string           `db:"country" json:"country"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	BusinessHours  []string         `db:"business_hours" json:"business_hours"`
	PaymentMethods []string         `db:"payment_methods" json:"payment_methods"`
	Products       []pgtype.UUID    `db:"products" json:"products"`
}

// FindStoreByID
//
//	WITH relevant_business_hours AS (
//	    SELECT id, weekday, open_hour, closing_hour
//	    FROM store_business_hour bh
//	    WHERE id = $1
//	),
//	     relevant_payment_methods AS (
//	         SELECT id, payment_method
//	         FROM store_payment_method pm
//	         WHERE id = $1
//	     ),
//	    relevant_products AS (
//	        SELECT id, store_id
//	        FROM product
//	        WHERE store_id = $1
//	    )
//	SELECT
//	    s.owner_id, s.cnpj, s.name, s.description,
//	    s.active, s.phone, s.score, s.is_open, s.type, s.delivery_time, s.profile_image,
//	    s.header_image, s.address_line_1, s.address_line_2, s.neighborhood,
//	    s.city, s.state, s.postal_code, s.latitude, s.longitude,
//	    s.country, s.created_at, s.updated_at, s.deleted_at,
//	    COALESCE(
//	        ARRAY_AGG(DISTINCT rbh.weekday || ' ' || rbh.open_hour || ' ' || rbh.closing_hour) FILTER (WHERE rbh.id IS NOT NULL),
//	                    '{}'::text[]
//	    )::text[] AS business_hours,
//	    COALESCE(
//	        ARRAY_AGG(DISTINCT rpm.payment_method) FILTER (WHERE rpm.id IS NOT NULL),
//	                    '{}'::"PaymentMethod"[]
//	    )::text[] AS payment_methods,
//	    COALESCE(
//	            ARRAY_AGG(DISTINCT rp.id) FILTER (WHERE rp.id IS NOT NULL),
//	                        '{}'::uuid[]
//	        )::uuid[] AS products
//	FROM store s
//	         LEFT JOIN relevant_business_hours rbh ON s.id = rbh.id
//	         LEFT JOIN relevant_payment_methods rpm ON s.id = rpm.id
//	         LEFT JOIN relevant_products rp ON s.id = rp.store_id
//	WHERE s.id = $1
//	GROUP BY
//	    s.owner_id, s.cnpj, s.name, s.description,
//	    s.active, s.phone, s.score, s.is_open, s.type, s.delivery_time, s.profile_image,
//	    s.header_image, s.address_line_1, s.address_line_2, s.neighborhood,
//	    s.city, s.state, s.postal_code, s.latitude, s.longitude,
//	    s.country, s.created_at, s.updated_at, s.deleted_at
func (q *Queries) FindStoreByID(ctx context.Context, id pgtype.UUID) (FindStoreByIDRow, error) {
	row := q.db.QueryRow(ctx, findStoreByID, id)
	var i FindStoreByIDRow
	err := row.Scan(
		&i.OwnerID,
		&i.Cnpj,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.Phone,
		&i.Score,
		&i.IsOpen,
		&i.Type,
		&i.DeliveryTime,
		&i.ProfileImage,
		&i.HeaderImage,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BusinessHours,
		&i.PaymentMethods,
		&i.Products,
	)
	return i, err
}

const findStoresByFilter = `-- name: FindStoresByFilter :many
SELECT
    s.id,
    s.name,
    s.score,
    s.is_open,
    s.type,
    s.delivery_time,
    s.neighborhood,
    s.latitude,
    s.longitude,
    s.profile_image,
    COUNT(*) OVER () AS total_items
FROM store s
WHERE 1 = 1
  AND (
    NULLIF($1::text, '') IS NULL
        OR unaccent(s.name) ILIKE '%' || unaccent($1::text) || '%'
    )
  AND (
    NULLIF($2::text, '') IS NULL
        OR s.type::text = $2
    )
  AND (
    NULLIF($3::text, '') IS NULL
        OR s.city = $3
    )
  AND (
      NULLIF($4::integer, 0) = 0
        or s.score >= $4
    )
  AND (
    $5::boolean IS NULL
        OR s.is_open = $5::boolean
    )
ORDER BY s.score DESC, s.type
OFFSET $6
    LIMIT $7
`

type FindStoresByFilterParams struct {
	Name        string      `db:"name" json:"name"`
	Type        string      `db:"type" json:"type"`
	City        string      `db:"city" json:"city"`
	Score       int32       `db:"score" json:"score"`
	IsOpen      pgtype.Bool `db:"is_open" json:"is_open"`
	OffsetValue int32       `db:"offset_value" json:"offset_value"`
	LimitItems  int32       `db:"limit_items" json:"limit_items"`
}

type FindStoresByFilterRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Score        int32       `db:"score" json:"score"`
	IsOpen       bool        `db:"is_open" json:"is_open"`
	Type         StoreType   `db:"type" json:"type"`
	DeliveryTime pgtype.Int4 `db:"delivery_time" json:"delivery_time"`
	Neighborhood string      `db:"neighborhood" json:"neighborhood"`
	Latitude     pgtype.Text `db:"latitude" json:"latitude"`
	Longitude    pgtype.Text `db:"longitude" json:"longitude"`
	ProfileImage pgtype.Text `db:"profile_image" json:"profile_image"`
	TotalItems   int64       `db:"total_items" json:"total_items"`
}

// FindStoresByFilter
//
//	SELECT
//	    s.id,
//	    s.name,
//	    s.score,
//	    s.is_open,
//	    s.type,
//	    s.delivery_time,
//	    s.neighborhood,
//	    s.latitude,
//	    s.longitude,
//	    s.profile_image,
//	    COUNT(*) OVER () AS total_items
//	FROM store s
//	WHERE 1 = 1
//	  AND (
//	    NULLIF($1::text, '') IS NULL
//	        OR unaccent(s.name) ILIKE '%' || unaccent($1::text) || '%'
//	    )
//	  AND (
//	    NULLIF($2::text, '') IS NULL
//	        OR s.type::text = $2
//	    )
//	  AND (
//	    NULLIF($3::text, '') IS NULL
//	        OR s.city = $3
//	    )
//	  AND (
//	      NULLIF($4::integer, 0) = 0
//	        or s.score >= $4
//	    )
//	  AND (
//	    $5::boolean IS NULL
//	        OR s.is_open = $5::boolean
//	    )
//	ORDER BY s.score DESC, s.type
//	OFFSET $6
//	    LIMIT $7
func (q *Queries) FindStoresByFilter(ctx context.Context, arg FindStoresByFilterParams) ([]FindStoresByFilterRow, error) {
	rows, err := q.db.Query(ctx, findStoresByFilter,
		arg.Name,
		arg.Type,
		arg.City,
		arg.Score,
		arg.IsOpen,
		arg.OffsetValue,
		arg.LimitItems,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindStoresByFilterRow
	for rows.Next() {
		var i FindStoresByFilterRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Score,
			&i.IsOpen,
			&i.Type,
			&i.DeliveryTime,
			&i.Neighborhood,
			&i.Latitude,
			&i.Longitude,
			&i.ProfileImage,
			&i.TotalItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isOwner = `-- name: IsOwner :one
SELECT EXISTS(SELECT 1 FROM owner WHERE id = $1)
`

// IsOwner
//
//	SELECT EXISTS(SELECT 1 FROM owner WHERE id = $1)
func (q *Queries) IsOwner(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, isOwner, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isOwnerOf = `-- name: IsOwnerOf :one
SELECT EXISTS(SELECT 1 FROM store WHERE owner_id = $1 AND id = $2)
`

type IsOwnerOfParams struct {
	OwnerID string      `db:"owner_id" json:"owner_id"`
	ID      pgtype.UUID `db:"id" json:"id"`
}

// IsOwnerOf
//
//	SELECT EXISTS(SELECT 1 FROM store WHERE owner_id = $1 AND id = $2)
func (q *Queries) IsOwnerOf(ctx context.Context, arg IsOwnerOfParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOwnerOf, arg.OwnerID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeOwner = `-- name: RemoveOwner :exec
DELETE FROM owner
WHERE id = $1
`

// RemoveOwner
//
//	DELETE FROM owner
//	WHERE id = $1
func (q *Queries) RemoveOwner(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, removeOwner, id)
	return err
}

const saveCustomer = `-- name: SaveCustomer :exec
INSERT INTO customer (id, name, last_name, cpf, email, phone, created_at, updated_at, deleted_at)
VALUES (
    $1, $2, $3,
    NULLIF($4::TEXT, ''),  -- converte string vazia em NULL
    $5, $6,
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC',
    NULL
)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    last_name = EXCLUDED.last_name,
    cpf = EXCLUDED.cpf,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone
WHERE customer.id = $1
`

type SaveCustomerParams struct {
	ID       string `db:"id" json:"id"`
	Name     string `db:"name" json:"name"`
	LastName string `db:"last_name" json:"last_name"`
	Cpf      string `db:"cpf" json:"cpf"`
	Email    string `db:"email" json:"email"`
	Phone    string `db:"phone" json:"phone"`
}

// SaveCustomer
//
//	INSERT INTO customer (id, name, last_name, cpf, email, phone, created_at, updated_at, deleted_at)
//	VALUES (
//	    $1, $2, $3,
//	    NULLIF($4::TEXT, ''),  -- converte string vazia em NULL
//	    $5, $6,
//	    NOW() AT TIME ZONE 'UTC',
//	    NOW() AT TIME ZONE 'UTC',
//	    NULL
//	)
//	ON CONFLICT (id) DO UPDATE
//	SET
//	    name = EXCLUDED.name,
//	    last_name = EXCLUDED.last_name,
//	    cpf = EXCLUDED.cpf,
//	    email = EXCLUDED.email,
//	    phone = EXCLUDED.phone
//	WHERE customer.id = $1
func (q *Queries) SaveCustomer(ctx context.Context, arg SaveCustomerParams) error {
	_, err := q.db.Exec(ctx, saveCustomer,
		arg.ID,
		arg.Name,
		arg.LastName,
		arg.Cpf,
		arg.Email,
		arg.Phone,
	)
	return err
}

const saveCustomerAddress = `-- name: SaveCustomerAddress :exec
INSERT INTO address (customer_id, name, address_line_1, address_line_2, neighborhood, city, state,
                     postal_code, latitude, longitude, country, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
ON CONFLICT (customer_id, address_line_1, address_line_2, postal_code) DO UPDATE
    SET
        name = EXCLUDED.name,
        neighborhood = EXCLUDED.neighborhood,
        city = EXCLUDED.city,
        state = EXCLUDED.state,
        latitude = EXCLUDED.latitude,
        longitude = EXCLUDED.longitude,
        country = EXCLUDED.country,
        updated_at = NOW() AT TIME ZONE 'UTC'
WHERE address.customer_id = $1
  AND address.address_line_1 = $3
  AND address.address_line_2 = $4
  AND address.postal_code = $8
`

type SaveCustomerAddressParams struct {
	CustomerID   string      `db:"customer_id" json:"customer_id"`
	Name         string      `db:"name" json:"name"`
	AddressLine1 string      `db:"address_line_1" json:"address_line_1"`
	AddressLine2 string      `db:"address_line_2" json:"address_line_2"`
	Neighborhood string      `db:"neighborhood" json:"neighborhood"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	PostalCode   string      `db:"postal_code" json:"postal_code"`
	Latitude     pgtype.Text `db:"latitude" json:"latitude"`
	Longitude    pgtype.Text `db:"longitude" json:"longitude"`
	Country      string      `db:"country" json:"country"`
}

// SaveCustomerAddress
//
//	INSERT INTO address (customer_id, name, address_line_1, address_line_2, neighborhood, city, state,
//	                     postal_code, latitude, longitude, country, created_at, updated_at, deleted_at)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
//	        $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
//	ON CONFLICT (customer_id, address_line_1, address_line_2, postal_code) DO UPDATE
//	    SET
//	        name = EXCLUDED.name,
//	        neighborhood = EXCLUDED.neighborhood,
//	        city = EXCLUDED.city,
//	        state = EXCLUDED.state,
//	        latitude = EXCLUDED.latitude,
//	        longitude = EXCLUDED.longitude,
//	        country = EXCLUDED.country,
//	        updated_at = NOW() AT TIME ZONE 'UTC'
//	WHERE address.customer_id = $1
//	  AND address.address_line_1 = $3
//	  AND address.address_line_2 = $4
//	  AND address.postal_code = $8
func (q *Queries) SaveCustomerAddress(ctx context.Context, arg SaveCustomerAddressParams) error {
	_, err := q.db.Exec(ctx, saveCustomerAddress,
		arg.CustomerID,
		arg.Name,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Latitude,
		arg.Longitude,
		arg.Country,
	)
	return err
}

const saveOwner = `-- name: SaveOwner :exec
INSERT INTO owner (id, signature_active, created_at, updated_at, deleted_at)
VALUES ($1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
ON CONFLICT (id) DO UPDATE
SET
    signature_active = excluded.signature_active,
    updated_at = NOW() AT TIME ZONE 'UTC'
`

type SaveOwnerParams struct {
	ID              string `db:"id" json:"id"`
	SignatureActive bool   `db:"signature_active" json:"signature_active"`
}

// SaveOwner
//
//	INSERT INTO owner (id, signature_active, created_at, updated_at, deleted_at)
//	VALUES ($1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
//	ON CONFLICT (id) DO UPDATE
//	SET
//	    signature_active = excluded.signature_active,
//	    updated_at = NOW() AT TIME ZONE 'UTC'
func (q *Queries) SaveOwner(ctx context.Context, arg SaveOwnerParams) error {
	_, err := q.db.Exec(ctx, saveOwner, arg.ID, arg.SignatureActive)
	return err
}

const saveProduct = `-- name: SaveProduct :exec
INSERT INTO product (id, store_id, sku, active_for_sale, promo_active, type, tag, name, description,
                     stock_quantity, score, image_url, details, price, promotional_price, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13, $14, $15,
        NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC')
ON CONFLICT (id) DO UPDATE
SET
    sku = excluded.sku,
    active_for_sale = excluded.active_for_sale,
    promo_active = excluded.promo_active,
    type = excluded.type,
    tag = excluded.tag,
    name = excluded.name,
    description = excluded.description,
    stock_quantity = excluded.stock_quantity,
    score = excluded.score,
    image_url = excluded.image_url,
    details = excluded.details,
    price = excluded.price,
    promotional_price = excluded.promotional_price,
    updated_at = NOW() AT TIME ZONE 'UTC'
WHERE product.id = $1 AND product.store_id = $2
`

type SaveProductParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	StoreID          pgtype.UUID `db:"store_id" json:"store_id"`
	Sku              pgtype.Text `db:"sku" json:"sku"`
	ActiveForSale    bool        `db:"active_for_sale" json:"active_for_sale"`
	PromoActive      bool        `db:"promo_active" json:"promo_active"`
	Type             ProductType `db:"type" json:"type"`
	Tag              string      `db:"tag" json:"tag"`
	Name             string      `db:"name" json:"name"`
	Description      string      `db:"description" json:"description"`
	StockQuantity    int32       `db:"stock_quantity" json:"stock_quantity"`
	Score            int32       `db:"score" json:"score"`
	ImageUrl         pgtype.Text `db:"image_url" json:"image_url"`
	Details          []byte      `db:"details" json:"details"`
	Price            int32       `db:"price" json:"price"`
	PromotionalPrice pgtype.Int4 `db:"promotional_price" json:"promotional_price"`
}

// SaveProduct
//
//	INSERT INTO product (id, store_id, sku, active_for_sale, promo_active, type, tag, name, description,
//	                     stock_quantity, score, image_url, details, price, promotional_price, created_at, updated_at)
//	VALUES ($1, $2, $3, $4, $5, $6, $7,
//	        $8, $9, $10, $11, $12, $13, $14, $15,
//	        NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC')
//	ON CONFLICT (id) DO UPDATE
//	SET
//	    sku = excluded.sku,
//	    active_for_sale = excluded.active_for_sale,
//	    promo_active = excluded.promo_active,
//	    type = excluded.type,
//	    tag = excluded.tag,
//	    name = excluded.name,
//	    description = excluded.description,
//	    stock_quantity = excluded.stock_quantity,
//	    score = excluded.score,
//	    image_url = excluded.image_url,
//	    details = excluded.details,
//	    price = excluded.price,
//	    promotional_price = excluded.promotional_price,
//	    updated_at = NOW() AT TIME ZONE 'UTC'
//	WHERE product.id = $1 AND product.store_id = $2
func (q *Queries) SaveProduct(ctx context.Context, arg SaveProductParams) error {
	_, err := q.db.Exec(ctx, saveProduct,
		arg.ID,
		arg.StoreID,
		arg.Sku,
		arg.ActiveForSale,
		arg.PromoActive,
		arg.Type,
		arg.Tag,
		arg.Name,
		arg.Description,
		arg.StockQuantity,
		arg.Score,
		arg.ImageUrl,
		arg.Details,
		arg.Price,
		arg.PromotionalPrice,
	)
	return err
}

const saveStore = `-- name: SaveStore :exec
INSERT INTO store (id, owner_id, cnpj, name, description, active, phone, score, is_open, type,
                   delivery_time, profile_image, header_image, address_line_1, address_line_2,
                   neighborhood, city, state, postal_code, country, latitude, longitude,
                   created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16,
        $17, $18, $19, $20, $21, $22,
        NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
ON CONFLICT (id) DO UPDATE
    SET
        cnpj = excluded.cnpj,
        name = excluded.name,
        description = excluded.description,
        active = excluded.active,
        phone = excluded.phone,
        score = excluded.score,
        is_open = excluded.is_open,
        type = excluded.type,
        delivery_time = excluded.delivery_time,
        profile_image = excluded.profile_image,
        header_image = excluded.header_image,
        address_line_1 = excluded.address_line_1,
        address_line_2 = excluded.address_line_2,
        neighborhood = excluded.neighborhood,
        city = excluded.city,
        state = excluded.state,
        postal_code = excluded.postal_code,
        country = excluded.country,
        latitude = excluded.latitude,
        longitude = excluded.longitude,
        updated_at = NOW() AT TIME ZONE 'UTC'
WHERE store.id = excluded.id
`

type SaveStoreParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	OwnerID      string      `db:"owner_id" json:"owner_id"`
	Cnpj         string      `db:"cnpj" json:"cnpj"`
	Name         string      `db:"name" json:"name"`
	Description  string      `db:"description" json:"description"`
	Active       bool        `db:"active" json:"active"`
	Phone        string      `db:"phone" json:"phone"`
	Score        int32       `db:"score" json:"score"`
	IsOpen       bool        `db:"is_open" json:"is_open"`
	Type         StoreType   `db:"type" json:"type"`
	DeliveryTime pgtype.Int4 `db:"delivery_time" json:"delivery_time"`
	ProfileImage pgtype.Text `db:"profile_image" json:"profile_image"`
	HeaderImage  pgtype.Text `db:"header_image" json:"header_image"`
	AddressLine1 string      `db:"address_line_1" json:"address_line_1"`
	AddressLine2 string      `db:"address_line_2" json:"address_line_2"`
	Neighborhood string      `db:"neighborhood" json:"neighborhood"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	PostalCode   string      `db:"postal_code" json:"postal_code"`
	Country      string      `db:"country" json:"country"`
	Latitude     pgtype.Text `db:"latitude" json:"latitude"`
	Longitude    pgtype.Text `db:"longitude" json:"longitude"`
}

// SaveStore
//
//	INSERT INTO store (id, owner_id, cnpj, name, description, active, phone, score, is_open, type,
//	                   delivery_time, profile_image, header_image, address_line_1, address_line_2,
//	                   neighborhood, city, state, postal_code, country, latitude, longitude,
//	                   created_at, updated_at, deleted_at)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
//	        $11, $12, $13, $14, $15, $16,
//	        $17, $18, $19, $20, $21, $22,
//	        NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
//	ON CONFLICT (id) DO UPDATE
//	    SET
//	        cnpj = excluded.cnpj,
//	        name = excluded.name,
//	        description = excluded.description,
//	        active = excluded.active,
//	        phone = excluded.phone,
//	        score = excluded.score,
//	        is_open = excluded.is_open,
//	        type = excluded.type,
//	        delivery_time = excluded.delivery_time,
//	        profile_image = excluded.profile_image,
//	        header_image = excluded.header_image,
//	        address_line_1 = excluded.address_line_1,
//	        address_line_2 = excluded.address_line_2,
//	        neighborhood = excluded.neighborhood,
//	        city = excluded.city,
//	        state = excluded.state,
//	        postal_code = excluded.postal_code,
//	        country = excluded.country,
//	        latitude = excluded.latitude,
//	        longitude = excluded.longitude,
//	        updated_at = NOW() AT TIME ZONE 'UTC'
//	WHERE store.id = excluded.id
func (q *Queries) SaveStore(ctx context.Context, arg SaveStoreParams) error {
	_, err := q.db.Exec(ctx, saveStore,
		arg.ID,
		arg.OwnerID,
		arg.Cnpj,
		arg.Name,
		arg.Description,
		arg.Active,
		arg.Phone,
		arg.Score,
		arg.IsOpen,
		arg.Type,
		arg.DeliveryTime,
		arg.ProfileImage,
		arg.HeaderImage,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
	)
	return err
}

const setOwner = `-- name: SetOwner :exec
INSERT INTO owner (id, signature_active, created_at, updated_at, deleted_at)
VALUES ($1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
`

type SetOwnerParams struct {
	ID              string `db:"id" json:"id"`
	SignatureActive bool   `db:"signature_active" json:"signature_active"`
}

// SetOwner
//
//	INSERT INTO owner (id, signature_active, created_at, updated_at, deleted_at)
//	VALUES ($1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
func (q *Queries) SetOwner(ctx context.Context, arg SetOwnerParams) error {
	_, err := q.db.Exec(ctx, setOwner, arg.ID, arg.SignatureActive)
	return err
}
