// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	//AddNewCustomerAddresses
	//
	//  INSERT INTO address (customer_id, name, address_line_1, address_line_2, neighborhood, city, state,
	//  postal_code, latitude, longitude, country, created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
	//          $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
	AddNewCustomerAddresses(ctx context.Context, arg []AddNewCustomerAddressesParams) *AddNewCustomerAddressesBatchResults
	//DeleteCustomerAddresses
	//
	//  DELETE FROM address
	//  WHERE customer_id = $1
	//      AND name = $2
	//      AND address_line_1 = $3
	//      AND address_line_2 = $4
	//      AND neighborhood = $5
	//      AND city = $6
	//    And state = $7
	//      AND postal_code = $8
	//      AND country = $9
	DeleteCustomerAddresses(ctx context.Context, arg []DeleteCustomerAddressesParams) *DeleteCustomerAddressesBatchResults
	//DeleteStoreBusinessHour
	//
	//  DELETE FROM store_business_hour bh
	//  WHERE bh.id = $1
	//  AND bh.weekday = $2
	//  AND bh.open_hour = $3
	//  AND bh.closing_hour = $4
	DeleteStoreBusinessHour(ctx context.Context, arg []DeleteStoreBusinessHourParams) *DeleteStoreBusinessHourBatchResults
	//DeleteStorePaymentMethods
	//
	//  DELETE FROM store_payment_method
	//  WHERE id = $1 AND payment_method = $2
	DeleteStorePaymentMethods(ctx context.Context, arg []DeleteStorePaymentMethodsParams) *DeleteStorePaymentMethodsBatchResults
	//FindAddressesByCustomerID
	//
	//  SELECT a.id, a.name, a.address_line_1, address_line_2, a.neighborhood, a.city, a.state, a.postal_code, a.country, a.latitude, a.longitude
	//  FROM address a
	//  WHERE a.customer_id = $1
	//  ORDER BY a.created_at DESC
	FindAddressesByCustomerID(ctx context.Context, customerID string) ([]FindAddressesByCustomerIDRow, error)
	//FindBusinessHourByStoreID
	//
	//  SELECT bh.weekday, bh.open_hour, bh.closing_hour
	//  FROM store_business_hour bh
	//  WHERE bh.id = $1
	FindBusinessHourByStoreID(ctx context.Context, id pgtype.UUID) ([]FindBusinessHourByStoreIDRow, error)
	//FindCustomerByID
	//
	//  SELECT c.id, c.name, c.last_name, c.cpf, c.email, c.phone
	//  FROM customer c
	//  WHERE c.id = $1
	//  LIMIT 1
	FindCustomerByID(ctx context.Context, id string) (FindCustomerByIDRow, error)
	//FindOwnerByID
	//
	//  SELECT o.id,
	//         signature_active,
	//         COALESCE(
	//                         ARRAY_AGG(DISTINCT s.id::uuid) FILTER (WHERE s.id IS NOT NULL),
	//                         '{}'::uuid[]
	//         )::uuid[] AS store_ids
	//  FROM owner o
	//           LEFT JOIN store s ON o.id = s.owner_id
	//  WHERE o.id = $1
	//  GROUP BY o.id, signature_active
	FindOwnerByID(ctx context.Context, id string) (FindOwnerByIDRow, error)
	//FindOwnerStores
	//
	//  SELECT id, name, active, type, delivery_time, score, is_open, profile_image, city, state, country
	//  FROM store
	//  WHERE owner_id = $1
	FindOwnerStores(ctx context.Context, ownerID string) ([]FindOwnerStoresRow, error)
	//FindPaymentMethodsByStoreID
	//
	//  SELECT pm.payment_method FROM store_payment_method pm
	//  WHERE id = $1
	FindPaymentMethodsByStoreID(ctx context.Context, id pgtype.UUID) ([]PaymentMethod, error)
	//FindProductByID
	//
	//  SELECT i.store_id, i.sku, i.active_for_sale, i.promo_active, i.type, i.tag, i.name,
	//         i.description, i.stock_quantity, i.score, i.image_url, i.details, i.price, i.promotional_price
	//  FROM product i
	//  WHERE i.id = $1
	//  LIMIT 1
	FindProductByID(ctx context.Context, id pgtype.UUID) (FindProductByIDRow, error)
	//FindProductsByStoreID
	//
	//  SELECT i.id, i.store_id, i.sku, i.active_for_sale, i.promo_active, i.type, i.tag, i.name,
	//         i.description, i.stock_quantity, i.score, i.image_url, i.details, i.price, i.promotional_price
	//  FROM product i
	//  WHERE i.store_id = $1
	FindProductsByStoreID(ctx context.Context, storeID pgtype.UUID) ([]FindProductsByStoreIDRow, error)
	//FindProductsIDByStoreID
	//
	//  SELECT p.id from product p
	//  WHERE p.store_id = $1
	FindProductsIDByStoreID(ctx context.Context, storeID pgtype.UUID) ([]pgtype.UUID, error)
	//FindStoreByID
	//
	//  WITH relevant_business_hours AS (
	//      SELECT id, weekday, open_hour, closing_hour
	//      FROM store_business_hour bh
	//      WHERE id = $1
	//  ),
	//       relevant_payment_methods AS (
	//           SELECT id, payment_method
	//           FROM store_payment_method pm
	//           WHERE id = $1
	//       ),
	//      relevant_products AS (
	//          SELECT id, store_id
	//          FROM product
	//          WHERE store_id = $1
	//      )
	//  SELECT
	//      s.owner_id, s.cnpj, s.name, s.description,
	//      s.active, s.phone, s.score, s.is_open, s.type, s.delivery_time, s.profile_image,
	//      s.header_image, s.address_line_1, s.address_line_2, s.neighborhood,
	//      s.city, s.state, s.postal_code, s.latitude, s.longitude,
	//      s.country, s.created_at, s.updated_at, s.deleted_at,
	//      COALESCE(
	//          ARRAY_AGG(DISTINCT rbh.weekday || ' ' || rbh.open_hour || ' ' || rbh.closing_hour) FILTER (WHERE rbh.id IS NOT NULL),
	//                      '{}'::text[]
	//      )::text[] AS business_hours,
	//      COALESCE(
	//          ARRAY_AGG(DISTINCT rpm.payment_method) FILTER (WHERE rpm.id IS NOT NULL),
	//                      '{}'::"PaymentMethod"[]
	//      )::text[] AS payment_methods,
	//      COALESCE(
	//              ARRAY_AGG(DISTINCT rp.id) FILTER (WHERE rp.id IS NOT NULL),
	//                          '{}'::uuid[]
	//          )::uuid[] AS products
	//  FROM store s
	//           LEFT JOIN relevant_business_hours rbh ON s.id = rbh.id
	//           LEFT JOIN relevant_payment_methods rpm ON s.id = rpm.id
	//           LEFT JOIN relevant_products rp ON s.id = rp.store_id
	//  WHERE s.id = $1
	//  GROUP BY
	//      s.owner_id, s.cnpj, s.name, s.description,
	//      s.active, s.phone, s.score, s.is_open, s.type, s.delivery_time, s.profile_image,
	//      s.header_image, s.address_line_1, s.address_line_2, s.neighborhood,
	//      s.city, s.state, s.postal_code, s.latitude, s.longitude,
	//      s.country, s.created_at, s.updated_at, s.deleted_at
	FindStoreByID(ctx context.Context, id pgtype.UUID) (FindStoreByIDRow, error)
	//FindStoresByFilter
	//
	//  SELECT
	//      s.id,
	//      s.name,
	//      s.score,
	//      s.is_open,
	//      s.type,
	//      s.delivery_time,
	//      s.neighborhood,
	//      s.latitude,
	//      s.longitude,
	//      s.profile_image,
	//      COUNT(*) OVER () AS total_items
	//  FROM store s
	//  WHERE 1 = 1
	//    AND (
	//      NULLIF($1::text, '') IS NULL
	//          OR unaccent(s.name) ILIKE '%' || unaccent($1::text) || '%'
	//      )
	//    AND (
	//      NULLIF($2::text, '') IS NULL
	//          OR s.type::text = $2
	//      )
	//    AND (
	//      NULLIF($3::text, '') IS NULL
	//          OR s.city = $3
	//      )
	//    AND (
	//        NULLIF($4::integer, 0) = 0
	//          or s.score >= $4
	//      )
	//    AND (
	//      $5::boolean IS NULL
	//          OR s.is_open = $5::boolean
	//      )
	//  ORDER BY s.score DESC, s.type
	//  OFFSET $6
	//      LIMIT $7
	FindStoresByFilter(ctx context.Context, arg FindStoresByFilterParams) ([]FindStoresByFilterRow, error)
	//IsOwner
	//
	//  SELECT EXISTS(SELECT 1 FROM owner WHERE id = $1)
	IsOwner(ctx context.Context, id string) (bool, error)
	//IsOwnerOf
	//
	//  SELECT EXISTS(SELECT 1 FROM store WHERE owner_id = $1 AND id = $2)
	IsOwnerOf(ctx context.Context, arg IsOwnerOfParams) (bool, error)
	//RemoveOwner
	//
	//  DELETE FROM owner
	//  WHERE id = $1
	RemoveOwner(ctx context.Context, id string) error
	//SaveCustomer
	//
	//  INSERT INTO customer (id, name, last_name, cpf, email, phone, created_at, updated_at, deleted_at)
	//  VALUES (
	//      $1, $2, $3,
	//      NULLIF($4::TEXT, ''),  -- converte string vazia em NULL
	//      $5, $6,
	//      NOW() AT TIME ZONE 'UTC',
	//      NOW() AT TIME ZONE 'UTC',
	//      NULL
	//  )
	//  ON CONFLICT (id) DO UPDATE
	//  SET
	//      name = EXCLUDED.name,
	//      last_name = EXCLUDED.last_name,
	//      cpf = EXCLUDED.cpf,
	//      email = EXCLUDED.email,
	//      phone = EXCLUDED.phone
	//  WHERE customer.id = $1
	SaveCustomer(ctx context.Context, arg SaveCustomerParams) error
	//SaveCustomerAddress
	//
	//  INSERT INTO address (customer_id, name, address_line_1, address_line_2, neighborhood, city, state,
	//                       postal_code, latitude, longitude, country, created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
	//          $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
	//  ON CONFLICT (customer_id, address_line_1, address_line_2, postal_code) DO UPDATE
	//      SET
	//          name = EXCLUDED.name,
	//          neighborhood = EXCLUDED.neighborhood,
	//          city = EXCLUDED.city,
	//          state = EXCLUDED.state,
	//          latitude = EXCLUDED.latitude,
	//          longitude = EXCLUDED.longitude,
	//          country = EXCLUDED.country,
	//          updated_at = NOW() AT TIME ZONE 'UTC'
	//  WHERE address.customer_id = $1
	//    AND address.address_line_1 = $3
	//    AND address.address_line_2 = $4
	//    AND address.postal_code = $8
	SaveCustomerAddress(ctx context.Context, arg SaveCustomerAddressParams) error
	//SaveOwner
	//
	//  INSERT INTO owner (id, signature_active, created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
	//  ON CONFLICT (id) DO UPDATE
	//  SET
	//      signature_active = excluded.signature_active,
	//      updated_at = NOW() AT TIME ZONE 'UTC'
	SaveOwner(ctx context.Context, arg SaveOwnerParams) error
	//SaveProduct
	//
	//  INSERT INTO product (id, store_id, sku, active_for_sale, promo_active, type, tag, name, description,
	//                       stock_quantity, score, image_url, details, price, promotional_price, created_at, updated_at)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7,
	//          $8, $9, $10, $11, $12, $13, $14, $15,
	//          NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC')
	//  ON CONFLICT (id) DO UPDATE
	//  SET
	//      sku = excluded.sku,
	//      active_for_sale = excluded.active_for_sale,
	//      promo_active = excluded.promo_active,
	//      type = excluded.type,
	//      tag = excluded.tag,
	//      name = excluded.name,
	//      description = excluded.description,
	//      stock_quantity = excluded.stock_quantity,
	//      score = excluded.score,
	//      image_url = excluded.image_url,
	//      details = excluded.details,
	//      price = excluded.price,
	//      promotional_price = excluded.promotional_price,
	//      updated_at = NOW() AT TIME ZONE 'UTC'
	//  WHERE product.id = $1 AND product.store_id = $2
	SaveProduct(ctx context.Context, arg SaveProductParams) error
	//SaveStore
	//
	//  INSERT INTO store (id, owner_id, cnpj, name, description, active, phone, score, is_open, type,
	//                     delivery_time, profile_image, header_image, address_line_1, address_line_2,
	//                     neighborhood, city, state, postal_code, country, latitude, longitude,
	//                     created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
	//          $11, $12, $13, $14, $15, $16,
	//          $17, $18, $19, $20, $21, $22,
	//          NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
	//  ON CONFLICT (id) DO UPDATE
	//      SET
	//          cnpj = excluded.cnpj,
	//          name = excluded.name,
	//          description = excluded.description,
	//          active = excluded.active,
	//          phone = excluded.phone,
	//          score = excluded.score,
	//          is_open = excluded.is_open,
	//          type = excluded.type,
	//          delivery_time = excluded.delivery_time,
	//          profile_image = excluded.profile_image,
	//          header_image = excluded.header_image,
	//          address_line_1 = excluded.address_line_1,
	//          address_line_2 = excluded.address_line_2,
	//          neighborhood = excluded.neighborhood,
	//          city = excluded.city,
	//          state = excluded.state,
	//          postal_code = excluded.postal_code,
	//          country = excluded.country,
	//          latitude = excluded.latitude,
	//          longitude = excluded.longitude,
	//          updated_at = NOW() AT TIME ZONE 'UTC'
	//  WHERE store.id = excluded.id
	SaveStore(ctx context.Context, arg SaveStoreParams) error
	//SaveStoreBusinessHour
	//
	//  INSERT INTO store_business_hour(id, weekday, open_hour, closing_hour)
	//  VALUES ($1, $2, $3, $4)
	SaveStoreBusinessHour(ctx context.Context, arg []SaveStoreBusinessHourParams) *SaveStoreBusinessHourBatchResults
	//SaveStorePaymentMethods
	//
	//  INSERT INTO store_payment_method (id, payment_method)
	//  VALUES ($1, $2)
	//  ON CONFLICT DO NOTHING
	SaveStorePaymentMethods(ctx context.Context, arg []SaveStorePaymentMethodsParams) *SaveStorePaymentMethodsBatchResults
	//SetOwner
	//
	//  INSERT INTO owner (id, signature_active, created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
	SetOwner(ctx context.Context, arg SetOwnerParams) error
}

var _ Querier = (*Queries)(nil)
