// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	//AddNewCustomerAddresses
	//
	//  INSERT INTO address (customer_id, name, address_line_1, address_line_2, neighborhood, city, state,
	//  postal_code, latitude, longitude, country, created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
	//          $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
	AddNewCustomerAddresses(ctx context.Context, arg []AddNewCustomerAddressesParams) *AddNewCustomerAddressesBatchResults
	//DeleteCustomerAddresses
	//
	//  DELETE FROM address
	//  WHERE customer_id = $1
	//      AND name = $2
	//      AND address_line_1 = $3
	//      AND address_line_2 = $4
	//      AND neighborhood = $5
	//      AND city = $6
	//    And state = $7
	//      AND postal_code = $8
	//      AND country = $9
	DeleteCustomerAddresses(ctx context.Context, arg []DeleteCustomerAddressesParams) *DeleteCustomerAddressesBatchResults
	//DeleteStoreBusinessHour
	//
	//  DELETE FROM store_business_hour bh
	//  WHERE bh.id = $1
	//  AND bh.weekday = $2
	//  AND bh.open_hour = $3
	//  AND bh.closing_hour = $4
	DeleteStoreBusinessHour(ctx context.Context, arg []DeleteStoreBusinessHourParams) *DeleteStoreBusinessHourBatchResults
	//DeleteStorePaymentMethods
	//
	//  DELETE FROM store_payment_method
	//  WHERE id = $1 AND payment_method = $2
	DeleteStorePaymentMethods(ctx context.Context, arg []DeleteStorePaymentMethodsParams) *DeleteStorePaymentMethodsBatchResults
	//FindAddressesByCustomerID
	//
	//  SELECT a.id, a.name, a.address_line_1, address_line_2, a.neighborhood, a.city, a.state, a.postal_code, a.country, a.latitude, a.longitude
	//  FROM address a
	//  WHERE a.customer_id = $1
	//  ORDER BY a.created_at DESC
	FindAddressesByCustomerID(ctx context.Context, customerID int64) ([]FindAddressesByCustomerIDRow, error)
	//FindBusinessHourByStoreID
	//
	//  SELECT bh.weekday, bh.open_hour, bh.closing_hour
	//  FROM store_business_hour bh
	//  WHERE bh.id = $1
	FindBusinessHourByStoreID(ctx context.Context, id pgtype.UUID) ([]FindBusinessHourByStoreIDRow, error)
	// noinspection SqlResolveForFile
	//
	//
	//  SELECT c.id, c.name, c.last_name, c.cpf, c.email, c.phone
	//  FROM customer c
	//  WHERE c.id = $1
	//  LIMIT 1
	FindCustomerByID(ctx context.Context, id int64) (FindCustomerByIDRow, error)
	//FindOwnerByID
	//
	//  SELECT o.id, signature_active from owner o
	//  WHERE o.id = $1
	FindOwnerByID(ctx context.Context, id int64) (FindOwnerByIDRow, error)
	//FindPaymentMethodsByStoreID
	//
	//  SELECT pm.payment_method FROM store_payment_method pm
	//  WHERE id = $1
	FindPaymentMethodsByStoreID(ctx context.Context, id pgtype.UUID) ([]PaymentMethod, error)
	//FindProductByID
	//
	//  SELECT i.store_id, i.sku, i.active_for_sale, i.promo_active, i.type, i.tag, i.name,
	//         i.description, i.stock_quantity, i.score, i.image_url, i.details, i.price, i.promotional_price
	//  FROM product i
	//  WHERE i.id = $1
	//  LIMIT 1
	FindProductByID(ctx context.Context, id pgtype.UUID) (FindProductByIDRow, error)
	//FindProductsIDByStoreID
	//
	//  SELECT p.id from product p
	//  WHERE p.store_id = $1
	FindProductsIDByStoreID(ctx context.Context, storeID pgtype.UUID) ([]pgtype.UUID, error)
	//FindStoreByID
	//
	//  WITH relevant_business_hours AS (
	//      SELECT id, weekday, open_hour, closing_hour
	//      FROM store_business_hour bh
	//      WHERE id = $1
	//  ),
	//       relevant_payment_methods AS (
	//           SELECT id, payment_method
	//           FROM store_payment_method pm
	//           WHERE id = $1
	//       )
	//  SELECT
	//      s.owner_id, s.cnpj, s.name, s.description,
	//      s.active, s.phone, s.score, s.is_open, s.type, s.profile_image,
	//      s.header_image, s.address_line_1, s.address_line_2, s.neighborhood,
	//      s.city, s.state, s.postal_code, s.latitude, s.longitude,
	//      s.country, s.created_at, s.updated_at, s.deleted_at,
	//      COALESCE(
	//          ARRAY_AGG(DISTINCT rbh.weekday || ' ' || rbh.open_hour || ' ' || rbh.closing_hour) FILTER (WHERE rbh.id IS NOT NULL),
	//                      '{}'::text[]
	//      )::text[] AS business_hours,
	//      COALESCE(
	//          ARRAY_AGG(DISTINCT rpm.payment_method) FILTER (WHERE rpm.id IS NOT NULL),
	//                      '{}'::"PaymentMethod"[]
	//      )::text[] AS payment_methods
	//  FROM store s
	//           LEFT JOIN relevant_business_hours rbh ON s.id = rbh.id
	//           LEFT JOIN relevant_payment_methods rpm ON s.id = rpm.id
	//  WHERE s.id = $1
	//  GROUP BY
	//      s.owner_id, s.cnpj, s.name, s.description,
	//      s.active, s.phone, s.score, s.is_open, s.type, s.profile_image,
	//      s.header_image, s.address_line_1, s.address_line_2, s.neighborhood,
	//      s.city, s.state, s.postal_code, s.latitude, s.longitude,
	//      s.country, s.created_at, s.updated_at, s.deleted_at
	FindStoreByID(ctx context.Context, id pgtype.UUID) (FindStoreByIDRow, error)
	//                    latitude, longitude, country, created_at, updated_at)
	// -- name: FindCustomerByID :many
	// SELECT c.id, c.name, c.last_name, c.cpf, c.email, c.phone, a.address_line_1, a.address_line_2,
	//        a.neighborhood, a.city, a.state, a.postal_code, a.country, o.id
	// FROM customer c
	// LEFT JOIN address a on c.id = a.customer_id
	// LEFT JOIN "order" o on c.id = o.customer_id;
	//
	// -- name: SaveCustomer :exec
	// INSERT INTO customer (id, name, last_name, cpf, email, phone, created_at, updated_at, deleted_at)
	//     VALUES ($1, $2, $3, $3, $5, $6,
	//             NOW() AT TIME ZONE 'UTC',
	//             NOW() AT TIME ZONE 'UTC',
	//             NULL)
	//     ON CONFLICT (id) DO UPDATE
	// SET
	//     name = $2,
	//     last_name = $3,
	//     cpf = $4,
	//     email = $5,
	//     phone = $6;
	// -- name: CreateStore :exec
	// INSERT INTO store (id, cpf_cnpj, owner_id, name, active, phone, score, type,
	//                    address_line_1, address_line_2, neighborhood, city, state, postal_code,
	//                    latitude, longitude, country, created_at, updated_at)
	// VALUES(
	//        $1,
	//        $2,
	//        $3,
	//        $4,
	//        $5,
	//        $6,
	//        $7,
	//        $8,
	//        $9,
	//        $10,
	//        $11,
	//        $12,
	//        $13,
	//        $14,
	//        $15,
	//        $16,
	//        $17,
	//        NOW() AT TIME ZONE 'UTC',
	//        NOW() AT TIME ZONE 'UTC');
	//
	// -- name: UpdateStore :exec
	// UPDATE store
	//   SET
	//     name = $3,
	//     phone = $4,
	//     type = $5,
	//     address_line_1 = $6,
	//     address_line_2 = $7,
	//     neighborhood = $8,
	//     city = $9,
	//     state = $10,
	//     postal_code = $11,
	//     country = $12,
	//     updated_at = NOW() AT TIME ZONE 'UTC'
	// WHERE id = $1 AND owner_id = $2;
	//
	// -- name: SetProfileImage :exec
	// UPDATE store
	//   SET
	//     profile_image = $2
	// WHERE id = $1;
	//
	// -- name: SetHeaderImage :exec
	// UPDATE store
	//   SET
	//     header_image = $2
	// WHERE id = $1;
	//
	// -- name: IsOwner :one
	// SELECT EXISTS(SELECT 1 FROM store WHERE id = $1 AND owner_id = $2);
	//
	// -- name: GetStoreByID :one
	// SELECT s.id, s.name, s.phone, s.score, s.type, s.address_line_1,
	// s.address_line_2, s.neighborhood, s.city, s.state, s.country, s.profile_image, s.header_image
	// FROM store s
	// WHERE id = $1;
	//
	// -- name: GetStoreBusinessHoursByID :many
	// SELECT week_day, timezone, opening_time, closing_time
	// FROM business_hour
	// WHERE store_id = $1
	// ORDER BY week_day;
	//
	//
	//
	//
	//
	//
	//
	//
	//  SELECT
	//      s.id,
	//      s.name,
	//      s.score,
	//      s.is_open,
	//      s.type,
	//      s.neighborhood,
	//      s.latitude,
	//      s.longitude,
	//      s.profile_image
	//  FROM store s
	//  WHERE (CASE
	//             WHEN $1::text IS NOT NULL
	//                 THEN s.name ILIKE '%' || $1::text || '%'
	//             ELSE true
	//      END)
	//    AND (CASE
	//             WHEN $2::text IS NOT NULL
	//                 THEN s.type::text = $2::text
	//             ELSE true
	//      END)
	//    AND (CASE
	//             WHEN $3::text IS NOT NULL
	//                 THEN s.city = $3::text
	//             ELSE true
	//      END)
	//    AND (CASE
	//             WHEN $4::boolean IS NOT NULL
	//                 THEN s.is_open = $4::boolean
	//             ELSE true
	//      END)
	//  ORDER BY s.score DESC, s.type
	//  OFFSET $5
	//  LIMIT $6
	FindStoresByFilter(ctx context.Context, arg FindStoresByFilterParams) ([]FindStoresByFilterRow, error)
	//IsOwner
	//
	//  SELECT EXISTS(SELECT 1 FROM owner WHERE id = $1)
	IsOwner(ctx context.Context, id int64) (bool, error)
	//RemoveOwner
	//
	//  DELETE FROM owner
	//  WHERE id = $1
	RemoveOwner(ctx context.Context, id int64) error
	//SaveCustomer
	//
	//  INSERT INTO customer (id, name, last_name, cpf, email, phone, created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, $3, $4, $5, $6,
	//          NOW() AT TIME ZONE 'UTC',
	//          NOW() AT TIME ZONE 'UTC',
	//          NULL)
	//  ON CONFLICT (id) DO UPDATE
	//      SET
	//          name = EXCLUDED.name,
	//          last_name = EXCLUDED.last_name,
	//          cpf = EXCLUDED.cpf,
	//          email = EXCLUDED.email,
	//          phone = EXCLUDED.phone
	//      WHERE customer.id = $1
	SaveCustomer(ctx context.Context, arg SaveCustomerParams) error
	//SaveCustomerAddress
	//
	//  INSERT INTO address (customer_id, name, address_line_1, address_line_2, neighborhood, city, state,
	//                       postal_code, latitude, longitude, country, created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
	//          $9, $10, $11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', NULL)
	//  ON CONFLICT (customer_id, address_line_1, address_line_2, postal_code) DO UPDATE
	//      SET
	//          name = EXCLUDED.name,
	//          neighborhood = EXCLUDED.neighborhood,
	//          city = EXCLUDED.city,
	//          state = EXCLUDED.state,
	//          latitude = EXCLUDED.latitude,
	//          longitude = EXCLUDED.longitude,
	//          country = EXCLUDED.country,
	//          updated_at = NOW() AT TIME ZONE 'UTC'
	//  WHERE address.customer_id = $1
	//    AND address.address_line_1 = $3
	//    AND address.address_line_2 = $4
	//    AND address.postal_code = $8
	SaveCustomerAddress(ctx context.Context, arg SaveCustomerAddressParams) error
	//SaveOwner
	//
	//  INSERT INTO owner (id, signature_active, created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
	//  ON CONFLICT (id) DO UPDATE
	//  SET
	//      signature_active = excluded.signature_active,
	//      updated_at = NOW() AT TIME ZONE 'UTC'
	SaveOwner(ctx context.Context, arg SaveOwnerParams) error
	//SaveProduct
	//
	//  INSERT INTO product (id, store_id, sku, active_for_sale, promo_active, type, tag, name, description,
	//                       stock_quantity, score, image_url, details, price, promotional_price, created_at, updated_at)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7,
	//          $8, $9, $10, $11, $12, $13, $14, $15,
	//          NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC')
	//  ON CONFLICT (id) DO UPDATE
	//  SET
	//      sku = excluded.sku,
	//      active_for_sale = excluded.active_for_sale,
	//      promo_active = excluded.promo_active,
	//      type = excluded.type,
	//      tag = excluded.tag,
	//      name = excluded.name,
	//      description = excluded.description,
	//      stock_quantity = excluded.stock_quantity,
	//      score = excluded.score,
	//      image_url = excluded.image_url,
	//      details = excluded.details,
	//      price = excluded.price,
	//      promotional_price = excluded.promotional_price,
	//      updated_at = NOW() AT TIME ZONE 'UTC'
	//  WHERE product.id = $1 AND product.store_id = $2
	SaveProduct(ctx context.Context, arg SaveProductParams) error
	//SaveStore
	//
	//  INSERT INTO store (id, owner_id, cnpj, name, description, active, phone, score, is_open, type,
	//                     profile_image, header_image, address_line_1, address_line_2,
	//                     neighborhood, city, state, postal_code, country, latitude, longitude,
	//                     created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
	//          $11, $12, $13, $14, $15, $16,
	//          $17, $18, $19, $20, $21,
	//          NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
	//  ON CONFLICT (id) DO UPDATE
	//      SET
	//          cnpj = excluded.cnpj,
	//          name = excluded.name,
	//          description = excluded.description,
	//          active = excluded.active,
	//          phone = excluded.phone,
	//          score = excluded.score,
	//          is_open = excluded.is_open,
	//          type = excluded.type,
	//          profile_image = excluded.profile_image,
	//          header_image = excluded.header_image,
	//          address_line_1 = excluded.address_line_1,
	//          address_line_2 = excluded.address_line_2,
	//          neighborhood = excluded.neighborhood,
	//          city = excluded.city,
	//          state = excluded.state,
	//          postal_code = excluded.postal_code,
	//          country = excluded.country,
	//          latitude = excluded.latitude,
	//          longitude = excluded.longitude,
	//          updated_at = NOW() AT TIME ZONE 'UTC'
	//  WHERE store.id = excluded.id
	SaveStore(ctx context.Context, arg SaveStoreParams) error
	//SaveStoreBusinessHour
	//
	//  INSERT INTO store_business_hour(id, weekday, open_hour, closing_hour)
	//  VALUES ($1, $2, $3, $4)
	SaveStoreBusinessHour(ctx context.Context, arg []SaveStoreBusinessHourParams) *SaveStoreBusinessHourBatchResults
	//SaveStorePaymentMethods
	//
	//  INSERT INTO store_payment_method (id, payment_method)
	//  VALUES ($1, $2)
	//  ON CONFLICT DO NOTHING
	SaveStorePaymentMethods(ctx context.Context, arg []SaveStorePaymentMethodsParams) *SaveStorePaymentMethodsBatchResults
	//SetOwner
	//
	//  INSERT INTO owner (id, signature_active, created_at, updated_at, deleted_at)
	//  VALUES ($1, $2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC', null)
	SetOwner(ctx context.Context, arg SetOwnerParams) error
}

var _ Querier = (*Queries)(nil)
