POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "teste123"
}

###

POST http://localhost:3000/api/v1/auth/sign-up
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "teste123",
  "profile": {
    "lastName": "Doe",
    "name": "John",
    "phone": "+5513995590867"
  }
}