// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Gustavo Ferreira de Jesus",
            "email": "gustavo081900@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/refresh": {
            "post": {
                "description": "Refresh an expired access token by providing a valid refresh token. Returns a new JWT if the refresh is successful.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh JWT using a refresh token",
                "parameters": [
                    {
                        "description": "Request body containing the refresh token.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authentication.RefreshParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns a new JWT upon successful token refresh.",
                        "schema": {
                            "$ref": "#/definitions/authentication.JWT"
                        }
                    },
                    "400": {
                        "description": "Bad request due to validation errors or malformed input.",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error, something went wrong while processing the request.",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway, likely due to an external service failure.",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/auth/sign-in": {
            "post": {
                "description": "Authenticate a user using their email and password. If successful, a JWT is returned which can be used for subsequent authenticated requests.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign-In with email and password",
                "parameters": [
                    {
                        "description": "Request body containing email and password.",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/authentication.SignInParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the generated JWT upon successful authentication.",
                        "schema": {
                            "$ref": "#/definitions/authentication.JWT"
                        }
                    },
                    "400": {
                        "description": "Bad request due to validation errors or malformed input.",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error, something went wrong while processing the request.",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway, likely due to an external service failure.",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/auth/sign-up": {
            "post": {
                "description": "Sign-Up with local credentials and data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign-Up with local credentials and data",
                "parameters": [
                    {
                        "description": "CreateUserParams",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/user.CreateParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/store": {
            "get": {
                "description": "Returns a list of stores based on various filter criteria including location, rating, and type.\nSupports geographic search with radius filtering when latitude and longitude are provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Search and filter stores",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum distance range in kilometers for geographical search",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum rating score (1-5)",
                        "name": "score",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Store name for partial matching",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by city name",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Latitude for geographical search (requires longitude)",
                        "name": "latitude",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Longitude for geographical search (requires latitude)",
                        "name": "longitude",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Store type category (e.g., restaurant, cafe, bar)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of stores matching the filter criteria",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.GetStoreByIdOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid filter parameters",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "404": {
                        "description": "No stores found",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Allows store owners to modify their store's details and settings.\nAll provided fields will be updated while maintaining existing data for omitted fields.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Update store information",
                "parameters": [
                    {
                        "description": "Updated store information including modifiable fields",
                        "name": "Params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.UpdateParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Store successfully updated"
                    },
                    "400": {
                        "description": "Invalid input parameters",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Bearer token missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User is not the store owner",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "404": {
                        "description": "Store not found",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "409": {
                        "description": "Conflict with existing data",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Allows authenticated users to register a new store in the system.\nThe store owner must provide essential information including name, location, and contact details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Create a new store",
                "parameters": [
                    {
                        "description": "Store creation parameters including name, address, contact info, and type",
                        "name": "Params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.CreateParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns the created store ID",
                        "schema": {
                            "$ref": "#/definitions/store.CreatedStore"
                        }
                    },
                    "400": {
                        "description": "Invalid input parameters",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Bearer token missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User lacks permission",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "409": {
                        "description": "Conflict - Store already exists",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/store/business-hours": {
            "put": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Allows store owners to set or update their store's operating hours.\nSupports setting different hours for each day of the week and special holiday schedules.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Add store business hours",
                "parameters": [
                    {
                        "description": "Business hours configuration including days, opening and closing times",
                        "name": "Params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.StoreBusinessHoursParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Business hours successfully updated"
                    },
                    "400": {
                        "description": "Invalid time format or parameters",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Bearer token missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User is not the store owner",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "409": {
                        "description": "Conflict with existing business hours",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Allows store owners to delete specific business hours or operating schedules.\nCan be used to remove regular hours or special holiday schedules.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Remove store business hours",
                "parameters": [
                    {
                        "description": "Business hours to be removed",
                        "name": "Params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.StoreBusinessHoursParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Business hours successfully deleted"
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Bearer token missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User is not the store owner",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "404": {
                        "description": "Business hours not found",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/store/item": {
            "get": {
                "description": "Returns a list of store items based on the provided filter criteria.\nSupports filtering by type, name, city, score, and maximum price.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Search and filter store items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by item type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by item name (partial match)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by store city",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by minimum score",
                        "name": "score",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by maximum price",
                        "name": "maxPrice",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of items matching the filter criteria",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/item.GetItemByIDOutput"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid filter parameters",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "404": {
                        "description": "No items found",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Modifies the details of an existing store item. Only authenticated store owners can update their own items.\nAll fields in the update request will replace the existing values.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Update an existing store item",
                "parameters": [
                    {
                        "description": "Updated item details including name, description, price, and availability",
                        "name": "Params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/item.UpdateItemInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item successfully updated"
                    },
                    "400": {
                        "description": "Invalid input parameters",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Bearer token missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User is not the store owner",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "409": {
                        "description": "Conflict with existing data",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Creates a new item in the store. Only authenticated store owners can perform this operation.\nThe item will be associated with the owner's store and available in the catalog.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Create a new store item",
                "parameters": [
                    {
                        "description": "Item creation parameters including name, description, price, and type",
                        "name": "Params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/item.CreateItemInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns the created item ID",
                        "schema": {
                            "$ref": "#/definitions/item.CreatedItem"
                        }
                    },
                    "400": {
                        "description": "Invalid input parameters",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Bearer token missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User is not the store owner",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "409": {
                        "description": "Conflict - Item already exists",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/store/item/{id}": {
            "get": {
                "description": "Returns detailed information about a specific store item by its ID.\nThis endpoint is publicly accessible and does not require authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Retrieve a specific store item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID - Unique identifier of the item",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item details including name, description, price, and availability",
                        "schema": {
                            "$ref": "#/definitions/item.GetItemByIDOutput"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Removes an item from the store catalog. Only authenticated store owners can delete their own items.\nThis operation is irreversible. All associated data will be permanently removed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Delete a store item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID to be deleted",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item successfully deleted"
                    },
                    "400": {
                        "description": "Invalid item ID",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Bearer token missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User is not the store owner",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "404": {
                        "description": "Item not found",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/store/{id}": {
            "get": {
                "description": "Returns detailed information about a store by its ID.\nThis endpoint is publicly accessible and provides store details including business hours,\ncontact information, location, and current status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Retrieve a specific store",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store ID - Unique identifier of the store",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Store details including name, description, business hours, and contact info",
                        "schema": {
                            "$ref": "#/definitions/store.GetStoreByIdOutput"
                        }
                    },
                    "404": {
                        "description": "Store not found",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/store/{id}/header-image": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Allows store owners to upload or update their store's header/banner image.\nSupports JPEG and PNG formats. Image will be processed and optimized for display.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Upload store header image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Header image file (JPEG/PNG only, max size: 5MB)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns URL of the uploaded image",
                        "schema": {
                            "$ref": "#/definitions/controller.setFileOutput"
                        }
                    },
                    "400": {
                        "description": "Invalid file format or size",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Bearer token missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User is not the store owner",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "413": {
                        "description": "File size exceeds limit",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/store/{id}/profile-image": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Allows store owners to upload or update their store's profile image.\nSupports JPEG and PNG formats. Image will be processed and optimized for display.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Upload store profile image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Profile image file (JPEG/PNG only, max size: 5MB)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns URL of the uploaded image",
                        "schema": {
                            "$ref": "#/definitions/controller.setFileOutput"
                        }
                    },
                    "400": {
                        "description": "Invalid file format or size",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Bearer token missing or invalid",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User is not the store owner",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "413": {
                        "description": "File size exceeds limit",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "put": {
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "User can update your profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User can update your profile",
                "parameters": [
                    {
                        "description": "UpdateProfileParams",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/user.UpdateProfileParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        },
        "/v1/user/roles": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    },
                    {
                        "Bearer Token": []
                    }
                ],
                "description": "Add a new role for user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Add a new role for user",
                "parameters": [
                    {
                        "description": "AddRolesParams",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/user.AddRolesParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/xerrors.CustomError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "address.Address": {
            "type": "object",
            "required": [
                "addressLine1",
                "addressLine2",
                "city",
                "country",
                "neighborhood",
                "postalCode",
                "state"
            ],
            "properties": {
                "addressLine1": {
                    "type": "string",
                    "maxLength": 40
                },
                "addressLine2": {
                    "type": "string",
                    "maxLength": 20
                },
                "city": {
                    "type": "string",
                    "maxLength": 25
                },
                "country": {
                    "type": "string",
                    "maxLength": 15
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "neighborhood": {
                    "type": "string",
                    "maxLength": 25
                },
                "postalCode": {
                    "type": "string",
                    "maxLength": 15
                },
                "state": {
                    "type": "string",
                    "maxLength": 15
                }
            }
        },
        "authentication.JWT": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eysjs9a..."
                },
                "expiresIn": {
                    "type": "integer",
                    "example": 300
                },
                "idToken": {
                    "type": "string",
                    "example": "eysjg54g3ba..."
                },
                "notBeforePolicy": {
                    "type": "integer",
                    "example": 150
                },
                "refreshExpiresIn": {
                    "type": "integer",
                    "example": 300
                },
                "refreshToken": {
                    "type": "string",
                    "example": "eynmiks.ewij..."
                },
                "scope": {
                    "type": "string",
                    "example": "email client user ..."
                },
                "sessionState": {
                    "type": "string",
                    "example": "634g43y3..."
                },
                "tokenType": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "authentication.RefreshParams": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string",
                    "example": "eyajbhhkd....."
                }
            }
        },
        "authentication.SignInParams": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "*********"
                }
            }
        },
        "controller.setFileOutput": {
            "type": "object",
            "properties": {
                "objectURL": {
                    "type": "string",
                    "example": "URL of object on storage"
                }
            }
        },
        "item.CreateItemInput": {
            "type": "object",
            "required": [
                "description",
                "name",
                "price",
                "storeID",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "The best burguer!"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string",
                    "maxLength": 25,
                    "example": "Hamburguer"
                },
                "price": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 2990
                },
                "storeID": {
                    "type": "string",
                    "example": "3279gbf23gb-fb23-6f239"
                },
                "type": {
                    "enum": [
                        "FOOD",
                        " WATERGALLON"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/item.Type"
                        }
                    ]
                }
            }
        },
        "item.CreatedItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "item.GetItemByIDOutput": {
            "type": "object",
            "required": [
                "active",
                "description",
                "discountActive",
                "discountPrice",
                "image",
                "name",
                "price",
                "score",
                "storeID",
                "type"
            ],
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "description": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "Com blend de 150g e molho especial."
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "discountActive": {
                    "type": "boolean",
                    "example": true
                },
                "discountPrice": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 2499
                },
                "image": {
                    "type": "string",
                    "example": "https://cardapiogo.com.br/fgbjkgr7erg793bj3lk"
                },
                "name": {
                    "type": "string",
                    "maxLength": 25,
                    "example": "Hambúrguer Artesanal"
                },
                "price": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 2990
                },
                "score": {
                    "type": "integer",
                    "example": 475
                },
                "storeID": {
                    "type": "string",
                    "example": "3279gbf23gb-fb23-6f239"
                },
                "type": {
                    "enum": [
                        "FOOD",
                        " WATERGALLON"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/item.Type"
                        }
                    ]
                }
            }
        },
        "item.Type": {
            "type": "string",
            "enum": [
                "FOOD",
                "WATERGALLON"
            ],
            "x-enum-varnames": [
                "Food",
                "WaterGallon"
            ]
        },
        "item.UpdateItemInput": {
            "type": "object",
            "required": [
                "active",
                "description",
                "discountActive",
                "discountPrice",
                "id",
                "name",
                "price",
                "storeID",
                "type"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string",
                    "maxLength": 50
                },
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "discountActive": {
                    "type": "boolean"
                },
                "discountPrice": {
                    "type": "integer",
                    "minimum": 0
                },
                "id": {
                    "type": "integer",
                    "example": 246643
                },
                "name": {
                    "type": "string",
                    "maxLength": 25
                },
                "price": {
                    "type": "integer",
                    "minimum": 0
                },
                "storeID": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "FOOD",
                        " WATERGALLON"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/item.Type"
                        }
                    ]
                }
            }
        },
        "store.AddressOutput": {
            "type": "object",
            "properties": {
                "addressLine1": {
                    "type": "string"
                },
                "addressLine2": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "neighborhood": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "store.BusinessHoursParams": {
            "type": "object",
            "required": [
                "closingTime",
                "openingTime"
            ],
            "properties": {
                "closingTime": {
                    "type": "string"
                },
                "openingTime": {
                    "type": "string"
                },
                "weekDay": {
                    "type": "integer",
                    "maximum": 6,
                    "minimum": 0
                }
            }
        },
        "store.CreateParams": {
            "type": "object",
            "required": [
                "address",
                "cpfCnpj",
                "name",
                "phone",
                "type"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/address.Address"
                },
                "cpfCnpj": {
                    "type": "string",
                    "example": "83193927805"
                },
                "name": {
                    "type": "string",
                    "maxLength": 25,
                    "example": "John"
                },
                "phone": {
                    "type": "string",
                    "example": "13997590579"
                },
                "type": {
                    "enum": [
                        "restaurant",
                        " pharmacy",
                        " tobbaco",
                        " market",
                        " convenience",
                        " pub"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/store.ShopType"
                        }
                    ]
                }
            }
        },
        "store.CreatedStore": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "store.GetStoreByIdOutput": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/store.AddressOutput"
                },
                "businessHours": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.BusinessHoursParams"
                    }
                },
                "headerImage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "paymentMethod": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "credit",
                            " debit",
                            " pix",
                            " cash"
                        ],
                        "$ref": "#/definitions/store.PaymentMethod"
                    }
                },
                "phone": {
                    "type": "string"
                },
                "profileImage": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "type": {
                    "enum": [
                        "restaurant",
                        " pharmacy",
                        " tobbaco",
                        " market",
                        " convenience",
                        " pub"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/store.ShopType"
                        }
                    ]
                }
            }
        },
        "store.PaymentMethod": {
            "type": "string",
            "enum": [
                "credit",
                "debit",
                "pix",
                "cash"
            ],
            "x-enum-varnames": [
                "Credit",
                "Debit",
                "Pix",
                "Cash"
            ]
        },
        "store.ShopType": {
            "type": "string",
            "enum": [
                "restaurant",
                "pharmacy",
                "tobbaco",
                "market",
                "convenience",
                "pub"
            ],
            "x-enum-varnames": [
                "Restaurant",
                "Pharmacy",
                "Tobbaco",
                "Market",
                "Convenience",
                "Pub"
            ]
        },
        "store.StoreBusinessHoursParams": {
            "type": "object",
            "required": [
                "id",
                "timeZone"
            ],
            "properties": {
                "businessHours": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.BusinessHoursParams"
                    }
                },
                "id": {
                    "type": "string"
                },
                "timeZone": {
                    "type": "string"
                }
            }
        },
        "store.UpdateParams": {
            "type": "object",
            "required": [
                "address",
                "id",
                "name",
                "phone",
                "type"
            ],
            "properties": {
                "address": {
                    "$ref": "#/definitions/address.Address"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 25
                },
                "paymentMethod": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "credit",
                            " debit",
                            " pix",
                            " cash"
                        ],
                        "$ref": "#/definitions/store.PaymentMethod"
                    }
                },
                "phone": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "restaurant",
                        " pharmacy",
                        " tobbaco",
                        " market",
                        " convenience",
                        " pub"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/store.ShopType"
                        }
                    ]
                }
            }
        },
        "user.AddRolesParams": {
            "type": "object",
            "required": [
                "roles"
            ],
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "consumer",
                            " delivery_man",
                            " owner",
                            " employee"
                        ],
                        "$ref": "#/definitions/user.Role"
                    }
                }
            }
        },
        "user.CreateParams": {
            "type": "object",
            "required": [
                "email",
                "password",
                "profile"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "johndoe@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "*********"
                },
                "profile": {
                    "$ref": "#/definitions/user.CreateProfileParams"
                }
            }
        },
        "user.CreateProfileParams": {
            "type": "object",
            "required": [
                "lastName",
                "name",
                "phone"
            ],
            "properties": {
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "phone": {
                    "type": "string",
                    "example": "13997590579"
                }
            }
        },
        "user.Role": {
            "type": "string",
            "enum": [
                "consumer",
                "owner",
                "employee",
                "delivery_man",
                "admin"
            ],
            "x-enum-varnames": [
                "RoleConsumer",
                "RoleOwner",
                "RoleEmployee",
                "RoleDeliveryMan",
                "RoleAdmin"
            ]
        },
        "user.UpdateProfileParams": {
            "type": "object",
            "required": [
                "lastName",
                "name",
                "phone"
            ],
            "properties": {
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "phone": {
                    "type": "string",
                    "example": "13997590579"
                }
            }
        },
        "xerrors.CustomError": {
            "type": "object",
            "properties": {
                "debug": {},
                "details": {},
                "error": {
                    "type": "string"
                },
                "traceID": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Cardapiogo API",
	Description:      "Documentação da API de delivery Cardapiogo.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
