name: Pull Request Pipeline

env:
  GO_VERSION: '1.26.2'

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true # O setup-go@v5 já faz o cache do Go automaticamente!

      - name: Download dependencies
        run: go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.0

  test:
    name: Run Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
        
      - name: Download dependencies
        run: go mod download

      - name: Create .env file
        run: |
          echo "APP_REPO=${{ github.event.repository.name }}" >> .env
          echo "APP_NAME=${{ github.event.repository.name }}" >> .env

      - name: Run Unit Tests
        run: make test-ci

      - name: Run Integration Tests
        run: make test-integration-ci